#include "gem_testing.h"
#include "werks_kvm.h"

#ifdef WERKS_HELP
CE_MESSAGE("compile with: -Wall -Wfatal-errors -I../include -I../src -o ../bin/werks_kvm_test ../src/kewl.c ../src/werks_kvm.c werks_kvm_test.c");
#endif

void map_looper(werks_kvm_type_dt t, char* k, void* v) {
    const char* n = werks_kvm_get_type_name(t);
    werks_kvm_type_dt u = werks_kvm_get_type_by_name(n);
    __auto char* z = concat_strings("typecheck ", n);
    Tests.run(z, strcmp(n, werks_kvm_get_type_name(u)) == 0);
    Tests.print("Key: %s | Type: %s | Value at: %p\n", k, n, v);
}

void map_looper_with_reference(werks_kvm_type_dt t, char* k, void* v, void* r) {
    const char* n = werks_kvm_get_type_name(t);
    werks_kvm_type_dt u = werks_kvm_get_type_by_name(n);
    __auto char* z = concat_strings("typecheck ", n);
    Tests.run(z, strcmp(n, werks_kvm_get_type_name(u)) == 0);
    Tests.print("Key: %s | Type: %s | Value at: %p | Reference: %p\n", k, n, v, r);
}

bool on_before_write_to_file(__unused werks_kvm_dt* map, const char* filename) {
    Tests.print("%s\n", filename);
    return false;
}

bool on_before_read_from_file(__unused werks_kvm_dt* map, const char* filename) {
    Tests.print("%s\n", filename);
    return false;
}

bool on_before_write_to_string(werks_kvm_dt* map) {
    Tests.print("%p\n", (void*)map);
    return false;
}

bool on_before_read_from_string(__unused werks_kvm_dt* map, const char* props) {
    Tests.print("%s\n", props);
    return false;
}

bool on_before_store_item(__unused werks_kvm_dt* map, const char* key, __unused werks_kvm_type_dt type, __unused void* value) {
    Tests.print("%s\n", key);
    return false;
}

bool on_before_delete_item(__unused werks_kvm_dt* map, const char* key) {
    Tests.print("%s\n", key);
    return false;
}

bool on_before_rename_item(__unused werks_kvm_dt* map, const char* key, const char* new_key) {
    Tests.print("%s -> %s\n", key, new_key);
    return false;
}

bool on_before_transfer_item(__unused werks_kvm_dt* map, const char* key, __unused werks_kvm_dt* destination_map, const char* destination_key) {
    Tests.print("%s => %s\n", key, destination_key);
    return false;
}

bool on_before_copy_item(__unused werks_kvm_dt* map, const char* key, __unused werks_kvm_dt* destination_map, const char* destination_key) {
    Tests.print("%s => %s\n", key, destination_key);
    return false;
}

int main(void) {
    Tests.begin("WeRKS KVM");
    werks_kvm_dt* ___map = werks_kvm_make();
    Tests.run("werks_kvm_make", assigned(___map));
    Tests.run("werks_kvm_get_component", assigned(werks_kvm_get_component(___map)));
    Tests.run("werks_kvm_is_packable NO", !werks_kvm_is_packable(___map));
    werks_kvm_dt* my_map = werks_kvm_create(10);
    Tests.run("werks_kvm_create", assigned(my_map));
    Tests.run("werks_kvm_is_packable NO", !werks_kvm_is_packable(my_map));
    Tests.run("werks_kvm_set_char", werks_kvm_set_char(my_map, "character", TEST_CHAR));
    Tests.run("werks_kvm_set_signed_char", werks_kvm_set_signed_char(my_map, "signed character", TEST_SIGNED_CHAR));
    Tests.run("werks_kvm_set_unsigned_char", werks_kvm_set_unsigned_char(my_map, "unsigned character", TEST_UNSIGNED_CHAR));
    Tests.run("werks_kvm_set_short", werks_kvm_set_short(my_map, "short integer", TEST_SHORT));
    Tests.run("werks_kvm_set_unsigned_short", werks_kvm_set_unsigned_short(my_map, "unsigned short integer", TEST_UNSIGNED_SHORT));
    Tests.run("werks_kvm_set_int", werks_kvm_set_int(my_map, "integer", TEST_INT));
    Tests.run("werks_kvm_set_unsigned_int", werks_kvm_set_unsigned_int(my_map, "unsigned integer", TEST_UNSIGNED_INT));
    Tests.run("werks_kvm_set_float", werks_kvm_set_float(my_map, "floating point", TEST_FLOAT));
    Tests.run("werks_kvm_set_double", werks_kvm_set_double(my_map, "double precision", TEST_DOUBLE));
    Tests.run("werks_kvm_set_string", werks_kvm_set_string(my_map, "string", TEST_STRING));
    Tests.run("werks_kvm_set_bool", werks_kvm_set_bool(my_map, "boolean", TEST_BOOL));
    Tests.run("werks_kvm_set_long", werks_kvm_set_long(my_map, "long integer", TEST_LONG_INT));
    Tests.run("werks_kvm_set_unsigned_long", werks_kvm_set_unsigned_long(my_map, "unsigned long integer", TEST_UNSIGNED_LONG_INT));
    Tests.run("werks_kvm_set_long_long", werks_kvm_set_long_long(my_map, "long long integer", TEST_LONG_LONG_INT));
    Tests.run("werks_kvm_set_unsigned_long_long", werks_kvm_set_unsigned_long_long(my_map, "unsigned long long integer", TEST_UNSIGNED_LONG_LONG_INT));
    Tests.run("werks_kvm_set_long_double", werks_kvm_set_long_double(my_map, "long double precision", TEST_LONG_DOUBLE));
    const char* z = "Hello World!";
    size_t zsz = strlen(z) + 1;
    Tests.run("werks_kvm_set_buffer", werks_kvm_set_buffer(my_map, "buffer", z, zsz));
    Tests.run("werks_kvm_set_int8", werks_kvm_set_int8(my_map, "int8", TEST_INT8));
    Tests.run("werks_kvm_set_uint8", werks_kvm_set_uint8(my_map, "uint8", TEST_UINT8));
    Tests.run("werks_kvm_set_int16", werks_kvm_set_int16(my_map, "int16", TEST_INT16));
    Tests.run("werks_kvm_set_uint16", werks_kvm_set_uint16(my_map, "uint16", TEST_UINT16));
    Tests.run("werks_kvm_set_int32", werks_kvm_set_int32(my_map, "int32", TEST_INT32));
    Tests.run("werks_kvm_set_uint32", werks_kvm_set_uint32(my_map, "uint32", TEST_UINT32));
    Tests.run("werks_kvm_set_int64", werks_kvm_set_int64(my_map, "int64", TEST_INT64));
    Tests.run("werks_kvm_set_uint64", werks_kvm_set_uint64(my_map, "uint64", TEST_UINT64));
    Tests.run("werks_kvm_is_top NULL", !werks_kvm_is_top(NULL));
    Tests.run("werks_kvm_is_top YES", werks_kvm_is_top(my_map));
    Tests.run("werks_kvm_set_kvm", werks_kvm_set_kvm(my_map, "nu_map"));
    werks_kvm_dt* nu_map = werks_kvm_get_kvm(my_map, "nu_map");
    Tests.run("werks_kvm_is_top NO", !werks_kvm_is_top(nu_map));
    Tests.run("werks_kvm_get_kvm", assigned(nu_map));
    Tests.run("werks_kvm_set_long nu_map", werks_kvm_set_long(nu_map, "long integer (at nu_map)", 987654321L));
    long* nu_long = werks_kvm_get_long(nu_map, "long integer (at nu_map)");
    Tests.run("werks_kvm_get_long nu_map", assigned(nu_long) && *nu_long == 987654321L);
    Tests.run("werks_kvm_set_long extra", werks_kvm_set_long(my_map, "extra long integer (at my_map)", 900000000L));

    Tests.run("werks_kvm_has_item NULL", !werks_kvm_has_item(my_map, NULL));
    Tests.run("werks_kvm_has_item inexistent", !werks_kvm_has_item(my_map, "inexistent"));
    Tests.run("werks_kvm_has_item ok", werks_kvm_has_item(my_map, "integer"));
    Tests.run("werks_kvm_has_typed_item NULL", !werks_kvm_has_typed_item(my_map, NULL, WERKS_KVM_TYPE_INT));
    Tests.run("werks_kvm_has_typed_item inexistent", !werks_kvm_has_typed_item(my_map, "inexistent", WERKS_KVM_TYPE_INT));
    Tests.run("werks_kvm_has_typed_item wrong", !werks_kvm_has_typed_item(my_map, "integer", WERKS_KVM_TYPE_FLOAT));
    Tests.run("werks_kvm_has_typed_item ok", werks_kvm_has_typed_item(my_map, "integer", WERKS_KVM_TYPE_INT));

    char* pChar = werks_kvm_get_char(my_map, "character");
    Tests.run("werks_kvm_get_char", *pChar == TEST_CHAR);
    Tests.print("Char: %c\n", *pChar);
    signed char* pSChar = werks_kvm_get_signed_char(my_map, "signed character");
    Tests.run("werks_kvm_get_signed_char", *pSChar == TEST_SIGNED_CHAR);
    Tests.print("Signed char: %hhd\n", *pSChar);
    unsigned char* pUChar = werks_kvm_get_unsigned_char(my_map, "unsigned character");
    Tests.run("werks_kvm_get_unsigned_char", *pUChar == TEST_UNSIGNED_CHAR);
    Tests.print("Unsigned char: %hhu\n", *pUChar);
    float* pFloat = werks_kvm_get_float(my_map, "floating point");
    Tests.run("werks_kvm_get_float", *pFloat == TEST_FLOAT);
    Tests.print("Float: %f\n", *pFloat);
    double* pDouble = werks_kvm_get_double(my_map, "double precision");
    Tests.run("werks_kvm_get_double", *pDouble == TEST_DOUBLE);
    Tests.print("Double: %lf\n", *pDouble);
    char* pString = werks_kvm_get_string(my_map, "string");
    Tests.run("werks_kvm_get_string", streq(pString, TEST_STRING));
    Tests.print("String: %s\n", pString);
    bool* pBool = werks_kvm_get_bool(my_map, "boolean");
    Tests.run("werks_kvm_get_bool", *pBool == TEST_BOOL);
    Tests.print("Bool: %s\n", *pBool ? "true" : "false");
    short* pShort = werks_kvm_get_short(my_map, "short integer");
    Tests.run("werks_kvm_get_short", *pShort == TEST_SHORT);
    Tests.print("Short int: %d\n", *pShort);
    unsigned short* pUShort = werks_kvm_get_unsigned_short(my_map, "unsigned short integer");
    Tests.run("werks_kvm_get_unsigned_short", *pUShort == TEST_UNSIGNED_SHORT);
    Tests.print("Unsigned short int: %d\n", *pUShort);
    int* pInt = werks_kvm_get_int(my_map, "integer");
    Tests.run("werks_kvm_get_int", *pInt == TEST_INT);
    Tests.print("Integer: %d\n", *pInt);
    unsigned int* pUInt = werks_kvm_get_unsigned_int(my_map, "unsigned integer");
    Tests.run("werks_kvm_get_unsigned_int", *pUInt == TEST_UNSIGNED_INT);
    Tests.print("Unsigned int: %u\n", *pUInt);
    long* pLong = werks_kvm_get_long(my_map, "long integer");
    Tests.run("werks_kvm_get_long", *pLong == TEST_LONG_INT);
    Tests.print("Long int: %ld\n", *pLong);
    unsigned long* pULong = werks_kvm_get_unsigned_long(my_map, "unsigned long integer");
    Tests.run("werks_kvm_get_unsigned_long", *pULong == TEST_UNSIGNED_LONG_INT);
    Tests.print("Unsigned long int: %lu\n", *pULong);
    long long* pLongLong = werks_kvm_get_long_long(my_map, "long long integer");
    Tests.run("werks_kvm_get_long_long", *pLongLong == TEST_LONG_LONG_INT);
    Tests.print("Long long int: %lld\n", *pLongLong);
    unsigned long long* pULongLong = werks_kvm_get_unsigned_long_long(my_map, "unsigned long long integer");
    Tests.run("werks_kvm_get_unsigned_long_long", *pULongLong == TEST_UNSIGNED_LONG_LONG_INT);
    Tests.print("Unsigned long long int: %llu\n", *pULongLong);
    long double* pLongDouble = werks_kvm_get_long_double(my_map, "long double precision");
    Tests.run("werks_kvm_get_long_double", *pLongDouble == TEST_LONG_DOUBLE);
    Tests.print("Long Double: %.*Lf\n", LDBL_DIG, *pLongDouble); // LDBL_DIG from <float.h> to get the maximum decimal digits of precision
    void* bpBuffer = werks_kvm_get_buffer_pointer(my_map, "buffer");
    Tests.run("werks_kvm_get_buffer_pointer", assigned(bpBuffer) && streq(bpBuffer, z));
    Tests.print("Buffer: %p [%s]\n", bpBuffer, (char*)bpBuffer);
    size_t szBuffer = werks_kvm_get_buffer_size(my_map, "buffer");
    Tests.run("werks_kvm_get_buffer_size", szBuffer == zsz);
    Tests.print("Buffer Size: %u\n", szBuffer);
    int8_t* pInt8 = werks_kvm_get_int8(my_map, "int8");
    Tests.run("werks_kvm_get_int8", *pInt8 == TEST_INT8);
    Tests.print("Int8: %d\n", *pInt8);
    uint8_t* pUInt8 = werks_kvm_get_uint8(my_map, "uint8");
    Tests.run("werks_kvm_get_uint8", *pUInt8 == TEST_UINT8);
    Tests.print("UInt8: %u\n", *pUInt8);
    int16_t* pInt16 = werks_kvm_get_int16(my_map, "int16");
    Tests.run("werks_kvm_get_int16", *pInt16 == TEST_INT16);
    Tests.print("Int16: %d\n", *pInt16);
    uint16_t* pUInt16 = werks_kvm_get_uint16(my_map, "uint16");
    Tests.run("werks_kvm_get_uint16", *pUInt16 == TEST_UINT16);
    Tests.print("UInt16: %u\n", *pUInt16);
    int32_t* pInt32 = werks_kvm_get_int32(my_map, "int32");
    Tests.run("werks_kvm_get_int32", *pInt32 == TEST_INT32);
    Tests.print("Int32: %d\n", *pInt32);
    uint32_t* pUInt32 = werks_kvm_get_uint32(my_map, "uint32");
    Tests.run("werks_kvm_get_uint32", *pUInt32 == TEST_UINT32);
    Tests.print("UInt32: %u\n", *pUInt32);
    int64_t* pInt64 = werks_kvm_get_int64(my_map, "int64");
    Tests.run("werks_kvm_get_int64", *pInt64 == TEST_INT64);
    Tests.print("Int64: %ld\n", *pInt64);
    uint64_t* pUInt64 = werks_kvm_get_uint64(my_map, "uint64");
    Tests.run("werks_kvm_get_uint64", *pUInt64 == TEST_UINT64);
    Tests.print("UInt64: %lu\n", *pUInt64);
    werks_kvm_dt* pMap = werks_kvm_get_kvm(my_map, "nu_map");
    Tests.run("werks_kvm_get_kvm", assigned(pMap));
    Tests.print("Map: %p [size: %ld]\n", (void*)pMap, werks_kvm_get_items_count(pMap));
    long* pMapLong = werks_kvm_get_long(pMap, "long integer (at nu_map)");
    Tests.run("werks_kvm_get_long nu_map", *pMapLong == *nu_long);
    Tests.run("werks_kvm_count_typed_items nu_map long 1", werks_kvm_count_typed_items(nu_map, WERKS_KVM_TYPE_LONG) == 1);
    Tests.run("werks_kvm_count_typed_items nu_map buffer 0", werks_kvm_count_typed_items(nu_map, WERKS_KVM_TYPE_BUFFER) == 0);
    long* xLong = werks_kvm_get_long(my_map, "nu_map\\long integer (at nu_map)");
    Tests.run("werks_kvm_get_long xpath YES", *xLong == *nu_long);
    Tests.print("%p\n", xLong);

    long* noLong = werks_kvm_get_long(my_map, "nu_map\\blah");
    Tests.run("werks_kvm_get_long xpath NO bad item", noLong == NULL);
    long* no2Long = werks_kvm_get_long(my_map, "nu_map\\blah\\blef");
    Tests.run("werks_kvm_get_long xpath NO bad branch", no2Long == NULL);
    long* no3Long = werks_kvm_get_long(my_map, "bar\\blah");
    Tests.run("werks_kvm_get_long xpath NO bad root", no3Long == NULL);
    long* no4Long = werks_kvm_get_long(my_map, "nu_map\\");
    Tests.run("werks_kvm_get_long xpath NO incomplete", no4Long == NULL);
    long* no5Long = werks_kvm_get_long(my_map, "\\");
    Tests.run("werks_kvm_get_long xpath NO invalid", no5Long == NULL);
    long* no6Long = werks_kvm_get_long(my_map, "\\long integer");
    Tests.run("werks_kvm_get_long xpath YES implicit root", *no6Long == *pLong);
    long* no7Long = werks_kvm_get_long(my_map, "\\nu_map\\long integer (at nu_map)");
    Tests.run("werks_kvm_get_long xpath YES implicit root with branches", *no7Long == *nu_long);

    Tests.run("werks_kvm_set_string string", werks_kvm_set_string(my_map, "string", "I Said Hello World!!!"));
    Tests.print("String: %s\n", werks_kvm_get_string(my_map, "string"));

    char* rv = werks_kvm_render_value_as_string(my_map, NULL);
    Tests.run("werks_kvm_render_value_as_string NO NULL", rv == NULL);
    rv = werks_kvm_render_value_as_string(my_map, "");
    Tests.run("werks_kvm_render_value_as_string NO empty", rv == NULL);
    rv = werks_kvm_render_value_as_string(my_map, "inexistent");
    Tests.run("werks_kvm_render_value_as_string NO inexistent", rv == NULL);
    rv = werks_kvm_render_value_as_string(my_map, "a\\b");
    Tests.run("werks_kvm_render_value_as_string NO nested", rv == NULL);
    rv = werks_kvm_render_value_as_string(my_map, "string");
    Tests.run("werks_kvm_render_value_as_string YES string", streq(rv, "I Said Hello World!!!"));
    Tests.print("%s\n", rv);
    free(rv);
    rv = werks_kvm_render_value_as_string(nu_map, "long integer (at nu_map)");
    Tests.run("werks_kvm_render_value_as_string YES long", streq(rv, "987654321"));
    Tests.print("%s\n", rv);
    free(rv);
    rv = werks_kvm_render_value_as_string(my_map, "character");
    Tests.run("werks_kvm_render_value_as_string YES character", streq(rv, "c"));
    Tests.print("%s\n", rv);
    free(rv);
    rv = werks_kvm_render_value_as_string(my_map, "buffer");
    Tests.run("werks_kvm_render_value_as_string YES buffer", streq(rv, "48656C6C6F20576F726C642100"));
    Tests.print("%s\n", rv);
    free(rv);

    werks_kvm_dt* c_kvm = werks_kvm_clone(my_map);
    Tests.run("werks_kvm_clone", assigned(c_kvm));
    Tests.run("werks_kvm_is_packable NO", !werks_kvm_is_packable(c_kvm));
    Tests.run("werks_kvm_contains_all_keys_of NULL c_map NO", !werks_kvm_contains_all_keys_of(NULL, c_kvm));
    Tests.run("werks_kvm_contains_all_keys_of c_map NULL NO", !werks_kvm_contains_all_keys_of(c_kvm, NULL));
    Tests.run("werks_kvm_contains_all_keys_of my_map c_map YES", werks_kvm_contains_all_keys_of(my_map, c_kvm));
    Tests.run("werks_kvm_contains_all_keys_of c_map my_map YES", werks_kvm_contains_all_keys_of(c_kvm, my_map));
    Tests.run("werks_kvm_same_keys YES", werks_kvm_same_keys(my_map, c_kvm));
    Tests.print("my_map: %d keys\n", werks_kvm_get_items_count(my_map));
    Tests.print("c_kvm: %d keys\n", werks_kvm_get_items_count(c_kvm));
    Tests.run("werks_kvm_contains_all_typed_keys_of NULL c_map NO", !werks_kvm_contains_all_typed_keys_of(NULL, c_kvm));
    Tests.run("werks_kvm_contains_all_typed_keys_of c_map NULL NO", !werks_kvm_contains_all_typed_keys_of(c_kvm, NULL));
    Tests.run("werks_kvm_contains_all_typed_keys_of my_map c_map YES", werks_kvm_contains_all_typed_keys_of(my_map, c_kvm));
    Tests.run("werks_kvm_contains_all_typed_keys_of c_map my_map YES", werks_kvm_contains_all_typed_keys_of(c_kvm, my_map));
    Tests.run("werks_kvm_same_typed_keys YES", werks_kvm_same_typed_keys(my_map, c_kvm));
    Tests.print("my_map: %d keys\n", werks_kvm_get_items_count(my_map));
    Tests.print("c_kvm: %d keys\n", werks_kvm_get_items_count(c_kvm));
    
    Tests.run("werks_kvm_set_string extra string", werks_kvm_set_string(my_map, "extra_string", "EXTRA!"));
    Tests.print("my_map['extra_string']: %s\n", werks_kvm_get_string(my_map, "extra_string"));

    Tests.run("werks_kvm_same_keys NO", !werks_kvm_same_keys(my_map, c_kvm));
    Tests.run("werks_kvm_same_typed_keys NO", !werks_kvm_same_typed_keys(my_map, c_kvm));
    Tests.run("werks_kvm_contains_all_keys_of my_map c_map YES", werks_kvm_contains_all_keys_of(my_map, c_kvm));
    Tests.run("werks_kvm_contains_all_keys_of c_map my_map NO", !werks_kvm_contains_all_keys_of(c_kvm, my_map));
    Tests.run("werks_kvm_contains_all_typed_keys_of my_map c_map YES", werks_kvm_contains_all_typed_keys_of(my_map, c_kvm));
    Tests.run("werks_kvm_contains_all_typed_keys_of c_map my_map NO", !werks_kvm_contains_all_typed_keys_of(c_kvm, my_map));

    Tests.run("werks_kvm_transfer_item no-map 1", !werks_kvm_transfer_item(NULL, "extra_string", c_kvm, "extra"));
    Tests.run("werks_kvm_transfer_item no-map 2", !werks_kvm_transfer_item(my_map, "extra_string", NULL, "extra"));
    Tests.run("werks_kvm_transfer_item no-key 1", !werks_kvm_transfer_item(my_map, NULL, c_kvm, "extra"));
    Tests.run("werks_kvm_transfer_item no-key 2", !werks_kvm_transfer_item(my_map, "extra_string", c_kvm, NULL));
    Tests.run("werks_kvm_transfer_item inexistent", !werks_kvm_transfer_item(my_map, "inexistent item", c_kvm, "extra"));
    Tests.run("werks_kvm_transfer_item already existent", !werks_kvm_transfer_item(my_map, "extra_string", c_kvm, "string"));
    Tests.run("werks_kvm_transfer_item ok", werks_kvm_transfer_item(my_map, "extra_string", c_kvm, "extra"));
    Tests.run("werks_kvm_has_item 1", !werks_kvm_has_item(my_map, "extra_string"));
    Tests.run("werks_kvm_has_item 2", werks_kvm_has_item(c_kvm, "extra"));
    Tests.print("c_kvm['extra']: %s\n", werks_kvm_get_string(c_kvm, "extra"));

    werks_kvm_dt* r_kvm = werks_kvm_make();
    Tests.run("werks_kvm_read_items", werks_kvm_read_items(r_kvm, my_map));
    Tests.print("r_kvm: %d keys\n", werks_kvm_get_items_count(r_kvm));
    Tests.print("my_map: %d keys\n", werks_kvm_get_items_count(my_map));
    Tests.run("werks_kvm_same_typed_keys YES", werks_kvm_same_typed_keys(r_kvm, my_map));
    Tests.run("werks_kvm_same_typed_keys NO", !werks_kvm_same_typed_keys(r_kvm, c_kvm));
    Tests.run("werks_kvm_is_top", werks_kvm_is_top(c_kvm));
    Tests.run("werks_kvm_is_top", werks_kvm_is_top(r_kvm));
    Tests.run("werks_kvm_filiate_to", werks_kvm_filiate_to(r_kvm, c_kvm, "filiated") && werks_kvm_has_typed_item(c_kvm, "filiated", WERKS_KVM_TYPE_KVM));
    Tests.run("werks_kvm_is_top", !werks_kvm_is_top(r_kvm));
    Tests.run("werks_kvm_is_top", werks_kvm_is_top(c_kvm));
    Tests.run("werks_kvm_get_parent", werks_kvm_get_parent(r_kvm) == c_kvm);
    Tests.run("werks_kvm_get_parent", werks_kvm_get_parent(c_kvm) == NULL);
    Tests.run("werks_kvm_has_item extra YES", werks_kvm_has_item(c_kvm, "extra"));
    Tests.run("werks_kvm_prefix_keys ((", werks_kvm_prefix_keys(c_kvm, "(("));
    Tests.run("werks_kvm_has_item extra NO", !werks_kvm_has_item(c_kvm, "extra"));
    Tests.run("werks_kvm_has_item ((extra YES", werks_kvm_has_item(c_kvm, "((extra"));
    Tests.run("werks_kvm_suffix_keys ))", werks_kvm_suffix_keys(c_kvm, "))"));
    Tests.run("werks_kvm_has_item ((extra NO", !werks_kvm_has_item(c_kvm, "((extra"));
    Tests.run("werks_kvm_has_item ((extra)) YES", werks_kvm_has_item(c_kvm, "((extra))"));
    Tests.run("werks_kvm_has_item extra)) NO", !werks_kvm_has_item(c_kvm, "extra))"));
    Tests.run("werks_kvm_unprefix_keys ((", werks_kvm_unprefix_keys(c_kvm, "(("));
    Tests.run("werks_kvm_has_item extra)) YES", werks_kvm_has_item(c_kvm, "extra))"));
    Tests.run("werks_kvm_has_item extra NO", !werks_kvm_has_item(c_kvm, "extra"));
    Tests.run("werks_kvm_unsuffix_keys ))", werks_kvm_unsuffix_keys(c_kvm, "))"));
    Tests.run("werks_kvm_has_item extra YES", werks_kvm_has_item(c_kvm, "extra"));
    werks_kvm_destroy(c_kvm);

    Tests.run("werks_kvm_get_on_before_write_to_string my_map", werks_kvm_get_on_before_write_to_string(my_map) == NULL);
    werks_kvm_set_on_before_write_to_string(my_map, on_before_write_to_string);
    Tests.run("werks_kvm_set_on_before_write_to_string my_map", werks_kvm_get_on_before_write_to_string(my_map) != NULL);
    Tests.run("werks_kvm_save_to_string my_map NO", werks_kvm_save_to_string(my_map) == NULL);
    werks_kvm_set_on_before_write_to_string(my_map, NULL);
    char* serialized = werks_kvm_save_to_string(my_map);
    Tests.run("werks_kvm_save_to_string my_map YES", has_content(serialized));
    Tests.print("-|||||||||||||||||||||||||||||-\n%s\n-|||||||||||||||||||||||||||||-\n", serialized);
    Tests.run("werks_kvm_get_on_before_read_from_string ___map", werks_kvm_get_on_before_read_from_string(___map) == NULL);
    werks_kvm_set_on_before_read_from_string(___map, on_before_read_from_string);
    Tests.run("werks_kvm_set_on_before_read_from_string ___map", werks_kvm_get_on_before_read_from_string(___map) != NULL);
    Tests.run("werks_kvm_read_from_string ___map NO", !werks_kvm_read_from_string(___map, serialized));
    werks_kvm_set_on_before_read_from_string(___map, NULL);
    Tests.run("werks_kvm_read_from_string ___map YES", werks_kvm_read_from_string(___map, serialized) && werks_kvm_get_items_count(___map) == werks_kvm_get_items_count(my_map));
    Tests.print("___map: %d keys\n", werks_kvm_get_items_count(___map));
    Tests.print("my_map: %d keys\n", werks_kvm_get_items_count(my_map));
    free(serialized);
    Tests.run("werks_kvm_are_events_allowed YES", werks_kvm_are_events_allowed(___map));
    werks_kvm_disable_events(___map);
    Tests.run("werks_kvm_are_events_allowed NO", !werks_kvm_are_events_allowed(___map));
    werks_kvm_enable_events(___map);
    Tests.run("werks_kvm_are_events_allowed again YES", werks_kvm_are_events_allowed(___map));
    Tests.run("werks_kvm_get_on_before_write_to_file ___map", werks_kvm_get_on_before_write_to_file(___map) == NULL);
    werks_kvm_set_on_before_write_to_file(___map, on_before_write_to_file);
    Tests.run("werks_kvm_set_on_before_write_to_file ___map", werks_kvm_get_on_before_write_to_file(___map) != NULL);
    Tests.run("werks_kvm_save_to_file ___map NO", !werks_kvm_save_to_file(___map, "test.map"));
    werks_kvm_set_on_before_write_to_file(___map, NULL);
    Tests.run("werks_kvm_save_to_file ___map YES", werks_kvm_save_to_file(___map, "test.map"));
    printf("werks_kvm_loop_items ___map\n");
    werks_kvm_loop_items(___map, map_looper);
    printf("--\n");
    werks_kvm_dt* l_map = werks_kvm_make();
    Tests.print("werks_kvm_get_capacity(l_map) = %ld\n", werks_kvm_get_capacity(l_map));
    werks_kvm_set_capacity_grow_factor(l_map, 1.5f);
    Tests.print("Capacity grow factor: %f\n", werks_kvm_get_capacity_grow_factor(l_map));
    werks_kvm_set_capacity_grow_padding(l_map, 0.5f);
    Tests.print("Capacity grow padding: %f\n", werks_kvm_get_capacity_grow_padding(l_map));
    Tests.run("werks_kvm_get_on_before_read_from_file l_map", werks_kvm_get_on_before_read_from_file(l_map) == NULL);
    werks_kvm_set_on_before_read_from_file(l_map, on_before_read_from_file);
    Tests.run("werks_kvm_set_on_before_read_from_file l_map", werks_kvm_get_on_before_read_from_file(l_map) != NULL);
    Tests.run("werks_kvm_read_from_file l_map NO", !werks_kvm_read_from_file(l_map, "test.map"));
    werks_kvm_set_on_before_read_from_file(l_map, NULL);
    Tests.run("werks_kvm_read_from_file", werks_kvm_read_from_file(l_map, "test.map") && werks_kvm_get_items_count(___map) == werks_kvm_get_items_count(l_map));
    Tests.print("werks_kvm_get_capacity(l_map) = %ld\n", werks_kvm_get_capacity(l_map));
    Tests.print("l_map: %d keys\n", werks_kvm_get_items_count(l_map));
    Tests.print("___map: %d keys\n", werks_kvm_get_items_count(___map));
    char* pC1 = werks_kvm_get_char(l_map, "character");
    Tests.run("werks_kvm_get_char", *pC1 == TEST_CHAR);
    Tests.print("Char: %c\n", *pC1);
    werks_kvm_destroy(l_map);
    werks_kvm_dt* f_map = werks_kvm_load_from_file("test.map");
    Tests.run("werks_kvm_load_from_file", werks_kvm_get_items_count(___map) == werks_kvm_get_items_count(f_map));
    Tests.print("f_map: %d keys\n", werks_kvm_get_items_count(f_map));
    Tests.print("___map: %d keys\n", werks_kvm_get_items_count(___map));
    char* pC2 = werks_kvm_get_char(f_map, "character");
    Tests.run("werks_kvm_get_char", *pC2 == TEST_CHAR);
    Tests.print("Char: %c\n", *pC2);
    Tests.run("werks_kvm_is_rename_allowed", werks_kvm_is_rename_allowed(f_map));
    Tests.run("werks_kvm_rename_item YES", werks_kvm_rename_item(f_map, "character", "renamed") && !werks_kvm_has_item(f_map, "character") && werks_kvm_has_item(f_map, "renamed"));
    werks_kvm_disable_rename(f_map);
    Tests.run("werks_kvm_disable_rename", !werks_kvm_is_rename_allowed(f_map));
    Tests.run("werks_kvm_rename_item NO", !werks_kvm_rename_item(f_map, "renamed", "character"));
    werks_kvm_enable_rename(f_map);
    Tests.run("werks_kvm_enable_rename", werks_kvm_is_rename_allowed(f_map));
    Tests.run("werks_kvm_rename_item YES", werks_kvm_rename_item(f_map, "renamed", "character"));
    Tests.run("werks_kvm_get_on_before_rename_item f_map", werks_kvm_get_on_before_rename_item(f_map) == NULL);
    werks_kvm_set_on_before_rename_item(f_map, on_before_rename_item);
    Tests.run("werks_kvm_set_on_before_rename_item f_map", werks_kvm_get_on_before_rename_item(f_map) != NULL);
    Tests.run("werks_kvm_rename_item f_map NO", !werks_kvm_rename_item(f_map, "character", "renamed"));
    werks_kvm_set_on_before_rename_item(f_map, NULL);
    Tests.run("werks_kvm_rename_item f_map YES", werks_kvm_rename_item(f_map, "character", "renamed") && !werks_kvm_has_item(f_map, "character") && werks_kvm_has_item(f_map, "renamed"));
    werks_kvm_destroy(f_map);
    
    long old_size = get_file_size("test.map");
    Tests.run("werks_kvm_append_to_file", werks_kvm_append_to_file(my_map, "test.map") && get_file_size("test.map") > old_size);
    delete_file("test.map");
    
    printf("werks_kvm_loop_items\n");
    werks_kvm_loop_items(my_map, map_looper);
    printf("werks_kvm_loop_items_with_reference\n");
    werks_kvm_loop_items_with_reference(my_map, map_looper_with_reference, my_map);
    printf("\n-- Only Strings:\n");
    printf("werks_kvm_loop_typed_items\n");
    werks_kvm_loop_typed_items(my_map, WERKS_KVM_TYPE_STRING, map_looper);
    printf("werks_kvm_loop_not_typed_items\n");
    werks_kvm_loop_not_typed_items(my_map, WERKS_KVM_TYPE_STRING, map_looper);
    printf("werks_kvm_loop_typed_items_with_reference\n");
    werks_kvm_loop_typed_items_with_reference(my_map, WERKS_KVM_TYPE_STRING, map_looper_with_reference, my_map);
    printf("werks_kvm_loop_not_typed_items_with_reference\n");
    werks_kvm_loop_not_typed_items_with_reference(my_map, WERKS_KVM_TYPE_STRING, map_looper_with_reference, my_map);
    Tests.run("werks_kvm_get_on_before_delete_item my_map", werks_kvm_get_on_before_delete_item(my_map) == NULL);
    werks_kvm_set_on_before_delete_item(my_map, on_before_delete_item);
    Tests.run("werks_kvm_set_on_before_delete_item my_map", werks_kvm_get_on_before_delete_item(my_map) != NULL);
    printf("werks_kvm_delete_item\n");
    Tests.run("werks_kvm_delete_item my_map NO", !werks_kvm_delete_item(my_map, "string"));
    werks_kvm_set_on_before_delete_item(my_map, NULL);
    Tests.run("werks_kvm_delete_item my_map YES", werks_kvm_delete_item(my_map, "string"));
    printf("\n-- And Again:\n");
    printf("werks_kvm_loop_typed_items\n");
    werks_kvm_loop_typed_items(my_map, WERKS_KVM_TYPE_STRING, map_looper);
    Tests.run("werks_kvm_set_string string2", werks_kvm_set_string(my_map, "string2", "And Hello World Again!!!"));
    Tests.print("String: %s\n", werks_kvm_get_string(my_map, "string2"));
    Tests.run("werks_kvm_delete_item", werks_kvm_delete_item(my_map, "string2"));
    Tests.print("Count: %zu | Size: %zu | Capacity: %zu\n", werks_kvm_get_items_count(my_map), werks_kvm_get_size(my_map), werks_kvm_get_capacity(my_map));
    Tests.run("werks_kvm_is_packable YES", werks_kvm_is_packable(my_map));
    Tests.run("werks_kvm_pack", werks_kvm_pack(my_map));
    Tests.print("Count: %zu | Size: %zu | Capacity: %zu\n", werks_kvm_get_items_count(my_map), werks_kvm_get_size(my_map), werks_kvm_get_capacity(my_map));
    Tests.run("werks_kvm_is_packable NO", !werks_kvm_is_packable(my_map));
    printf("werks_kvm_delete_typed_items\n");
    werks_kvm_delete_typed_items(my_map, WERKS_KVM_TYPE_BOOL);
    Tests.run("werks_kvm_is_packable YES", werks_kvm_is_packable(my_map));
    Tests.run("werks_kvm_pack", werks_kvm_pack(my_map));
    Tests.print("Count: %zu | Size: %zu | Capacity: %zu\n", werks_kvm_get_items_count(my_map), werks_kvm_get_size(my_map), werks_kvm_get_capacity(my_map));
    Tests.run("werks_kvm_is_packable NO", !werks_kvm_is_packable(my_map));
    printf("\n-- Force Reuse (delete+set+pack gives same capacity):\n");
    printf("werks_kvm_delete_typed_items\n");
    werks_kvm_delete_typed_items(my_map, WERKS_KVM_TYPE_INT);
    Tests.run("werks_kvm_is_packable YES", werks_kvm_is_packable(my_map));
    Tests.run("werks_kvm_get_on_before_store_item ___map", werks_kvm_get_on_before_store_item(___map) == NULL);
    werks_kvm_set_on_before_store_item(___map, on_before_store_item);
    Tests.run("werks_kvm_set_on_before_store_item ___map", werks_kvm_get_on_before_store_item(___map) != NULL);
    Tests.run("werks_kvm_set_int integer2 NO", werks_kvm_set_int(my_map, "integer2", 42));
    werks_kvm_set_on_before_store_item(___map, NULL);
    Tests.run("werks_kvm_set_int integer2 YES", werks_kvm_set_int(my_map, "integer2", 42));;
    Tests.run("werks_kvm_pack", werks_kvm_pack(my_map));
    Tests.print("Count: %zu | Size: %zu | Capacity: %zu\n", werks_kvm_get_items_count(my_map), werks_kvm_get_size(my_map), werks_kvm_get_capacity(my_map));
    Tests.run("werks_kvm_is_packable NO", !werks_kvm_is_packable(my_map));
    printf("\n---\n");
    Tests.run("werks_kvm_transfer_typed_items YES", werks_kvm_transfer_typed_items(my_map, WERKS_KVM_TYPE_INT, ___map) && !werks_kvm_has_item(my_map, "integer2") && werks_kvm_has_item(___map, "integer2"));
    Tests.run("werks_kvm_transfer_typed_items NO", !werks_kvm_transfer_typed_items(my_map, WERKS_KVM_TYPE_INT, ___map));
    Tests.run("werks_kvm_get_on_before_transfer_item ___map", werks_kvm_get_on_before_transfer_item(___map) == NULL);
    werks_kvm_set_on_before_transfer_item(___map, on_before_transfer_item);
    Tests.run("werks_kvm_set_on_before_transfer_item ___map", werks_kvm_get_on_before_transfer_item(___map) != NULL);
    Tests.run("werks_kvm_transfer_item ___map NO", !werks_kvm_transfer_item(___map, "integer2", my_map, "integer2"));
    werks_kvm_set_on_before_transfer_item(___map, NULL);
    Tests.run("werks_kvm_transfer_item ___map YES", werks_kvm_transfer_item(___map, "integer2", my_map, "integer2") && !werks_kvm_has_item(___map, "integer2") && werks_kvm_has_item(my_map, "integer2"));
    werks_kvm_destroy(my_map); // nu_map will be freed too
    werks_kvm_destroy(___map);
    werks_kvm_dt* a_map = werks_kvm_load_from_string("str1=(string)Hello\nstr2=(string)World\nnum=(short)123");
    Tests.run("werks_kvm_load_from_string", werks_kvm_get_items_count(a_map) == 3);
    werks_kvm_dt* b_map = werks_kvm_make();
    Tests.run("werks_kvm_get_items_count b_map 0", werks_kvm_get_items_count(b_map) == 0);
    Tests.run("werks_kvm_get_on_before_copy_item a_map", werks_kvm_get_on_before_copy_item(a_map) == NULL);
    werks_kvm_set_on_before_copy_item(a_map, on_before_copy_item);
    Tests.run("werks_kvm_set_on_before_copy_item a_map", werks_kvm_get_on_before_copy_item(a_map) != NULL);
    Tests.run("werks_kvm_copy_item a_map NO", !werks_kvm_copy_item(a_map, "num", b_map, "num_copy"));
    werks_kvm_set_on_before_copy_item(a_map, NULL);
    Tests.run("werks_kvm_copy_item a_map YES", werks_kvm_copy_item(a_map, "num", b_map, "num_copy"));
    Tests.run("werks_kvm_has_items_not_typed YES", werks_kvm_has_items_not_typed(b_map, WERKS_KVM_TYPE_LONG));
    Tests.run("werks_kvm_has_items_not_typed NO", !werks_kvm_has_items_not_typed(b_map, WERKS_KVM_TYPE_SHORT));
    Tests.run("werks_kvm_has_items_not_prefixed YES", werks_kvm_has_items_not_prefixed(b_map, "str"));
    Tests.run("werks_kvm_has_items_not_prefixed NO", !werks_kvm_has_items_not_prefixed(b_map, "num"));
    Tests.run("werks_kvm_has_items_not_suffixed YES", werks_kvm_has_items_not_suffixed(b_map, "str"));
    Tests.run("werks_kvm_has_items_not_suffixed NO", !werks_kvm_has_items_not_suffixed(b_map, "num"));
    Tests.run("werks_kvm_copy_typed_items", werks_kvm_copy_typed_items(a_map, WERKS_KVM_TYPE_STRING, b_map));
    Tests.run("werks_kvm_count_typed_items a_map short 1", werks_kvm_count_typed_items(a_map, WERKS_KVM_TYPE_SHORT) == 1);
    Tests.print("%d\n", werks_kvm_get_short(a_map, "num"));
    Tests.run("werks_kvm_count_typed_items a_map string 2", werks_kvm_count_typed_items(a_map, WERKS_KVM_TYPE_STRING) == 2);
    Tests.print("%s\n", werks_kvm_get_string(a_map, "str1"));
    Tests.print("%s\n", werks_kvm_get_string(a_map, "str2"));
    Tests.run("werks_kvm_get_items_count b_map 2", werks_kvm_get_items_count(b_map) == 3);
    Tests.run("werks_kvm_count_typed_items b_map short 1", werks_kvm_count_typed_items(b_map, WERKS_KVM_TYPE_SHORT) == 1);
    Tests.print("%d\n", werks_kvm_get_short(b_map, "num_copy"));
    Tests.run("werks_kvm_count_typed_items b_map string 2", werks_kvm_count_typed_items(b_map, WERKS_KVM_TYPE_STRING) == 2);
    Tests.print("%s\n", werks_kvm_get_string(b_map, "str1"));
    Tests.print("%s\n", werks_kvm_get_string(b_map, "str2"));
    Tests.run("werks_kvm_prefix_keys ++", werks_kvm_prefix_keys(a_map, "++"));
    Tests.run("werks_kvm_set_short", werks_kvm_set_short(a_map, "num2", TEST_SHORT));
    Tests.run("werks_kvm_copy_prefixed_items", werks_kvm_copy_prefixed_items(a_map, "++", b_map));
    Tests.run("werks_kvm_count_typed_items b_map short 2", werks_kvm_count_typed_items(b_map, WERKS_KVM_TYPE_SHORT) == 2);
    Tests.print("%d\n", werks_kvm_get_short(b_map, "++num"));
    Tests.run("werks_kvm_count_typed_items b_map string 4", werks_kvm_count_typed_items(b_map, WERKS_KVM_TYPE_STRING) == 4);
    Tests.print("%s\n", werks_kvm_get_string(b_map, "++str1"));
    Tests.print("%s\n", werks_kvm_get_string(b_map, "++str2"));
    Tests.run("werks_kvm_copy_suffixed_items", werks_kvm_copy_suffixed_items(a_map, "2", b_map));
    Tests.run("werks_kvm_count_typed_items b_map short 3", werks_kvm_count_typed_items(b_map, WERKS_KVM_TYPE_SHORT) == 3);
    Tests.print("%d\n", werks_kvm_get_short(b_map, "num2"));
    Tests.run("werks_kvm_has_items_typed NO", !werks_kvm_has_items_typed(b_map, WERKS_KVM_TYPE_LONG));
    Tests.run("werks_kvm_has_items_typed YES", werks_kvm_has_items_typed(b_map, WERKS_KVM_TYPE_SHORT));
    Tests.run("werks_kvm_get_items_count b_map 7", werks_kvm_get_items_count(b_map) == 7);
    werks_kvm_clear(a_map);
    Tests.run("werks_kvm_clear a_map", werks_kvm_get_items_count(a_map) == 0);
    Tests.run("werks_kvm_has_items_prefixed YES", werks_kvm_has_items_prefixed(b_map, "++"));
    Tests.run("werks_kvm_transfer_prefixed_items", werks_kvm_transfer_prefixed_items(b_map, "++", a_map));
    Tests.run("werks_kvm_has_items_prefixed NO", !werks_kvm_has_items_prefixed(b_map, "++"));
    Tests.run("werks_kvm_has_items_suffixed YES", werks_kvm_has_items_suffixed(b_map, "2"));
    Tests.run("werks_kvm_transfer_suffixed_items", werks_kvm_transfer_suffixed_items(b_map, "2", a_map));
    Tests.run("werks_kvm_has_items_suffixed NO", !werks_kvm_has_items_suffixed(b_map, "2"));
    Tests.run("werks_kvm_get_items_count b_map 2", werks_kvm_get_items_count(b_map) == 2);
    Tests.run("werks_kvm_count_typed_items a_map short 2", werks_kvm_count_typed_items(a_map, WERKS_KVM_TYPE_SHORT) == 2);
    Tests.print("%ld\n", werks_kvm_count_typed_items(a_map, WERKS_KVM_TYPE_SHORT));
    Tests.run("werks_kvm_count_typed_items a_map string 3", werks_kvm_count_typed_items(a_map, WERKS_KVM_TYPE_STRING) == 3);
    Tests.print("%ld\n", werks_kvm_count_typed_items(a_map, WERKS_KVM_TYPE_STRING));
    Tests.run("werks_kvm_get_items_count a_map 5", werks_kvm_get_items_count(a_map) == 5);
    Tests.run("werks_kvm_count_prefixed_items a_map ++ 3", werks_kvm_count_prefixed_items(a_map, "++") == 3);
    Tests.run("werks_kvm_count_not_prefixed_items a_map ++ 2", werks_kvm_count_not_prefixed_items(a_map, "++") == 2);
    Tests.run("werks_kvm_count_suffixed_items a_map 2 3", werks_kvm_count_suffixed_items(a_map, "2") == 3);
    Tests.run("werks_kvm_count_not_suffixed_items a_map 2 2", werks_kvm_count_not_suffixed_items(a_map, "2") == 2);
    Tests.run("werks_kvm_get_joined_keys NULL NULL", werks_kvm_get_joined_keys(NULL, NULL) == NULL);
    Tests.run("werks_kvm_get_joined_keys NULL ##", werks_kvm_get_joined_keys(NULL, "##") == NULL);
    Tests.run("werks_kvm_get_joined_keys a_map NULL", werks_kvm_get_joined_keys(a_map, NULL) == NULL);
    char* jk = werks_kvm_get_joined_keys(a_map, "##");
    Tests.run("werks_kvm_get_joined_keys a_map ##", has_content(jk));
    Tests.print("%s\n", jk);
    free(jk);
    printf("werks_kvm_loop_prefixed_items a_map\n");
    werks_kvm_loop_prefixed_items(a_map, "++", map_looper);
    printf("--\n");
    printf("werks_kvm_loop_not_prefixed_items a_map\n");
    werks_kvm_loop_not_prefixed_items(a_map, "++", map_looper);
    printf("--\n");
    printf("werks_kvm_loop_suffixed_items a_map\n");
    werks_kvm_loop_suffixed_items(a_map, "2", map_looper);
    printf("--\n");
    printf("werks_kvm_loop_not_suffixed_items a_map\n");
    werks_kvm_loop_not_suffixed_items(a_map, "2", map_looper);
    printf("--\n");
    printf("werks_kvm_loop_prefixed_items_with_reference a_map\n");
    werks_kvm_loop_prefixed_items_with_reference(a_map, "++", map_looper_with_reference, NULL);
    printf("--\n");
    printf("werks_kvm_loop_not_prefixed_items_with_reference a_map\n");
    werks_kvm_loop_not_prefixed_items_with_reference(a_map, "++", map_looper_with_reference, NULL);
    printf("--\n");
    printf("werks_kvm_loop_suffixed_items_with_reference a_map\n");
    werks_kvm_loop_suffixed_items_with_reference(a_map, "2", map_looper_with_reference, NULL);
    printf("--\n");
    printf("werks_kvm_loop_not_suffixed_items_with_reference a_map\n");
    werks_kvm_loop_not_suffixed_items_with_reference(a_map, "2", map_looper_with_reference, NULL);
    printf("--\n");
    printf("werks_kvm_delete_prefixed_items a_map\n");
    werks_kvm_delete_prefixed_items(a_map, "++");
    printf("werks_kvm_delete_suffixed_items a_map\n");
    werks_kvm_delete_suffixed_items(a_map, "2");
    Tests.run("werks_kvm_get_items_count a_map 0", werks_kvm_get_items_count(a_map) == 0);
    werks_kvm_destroy(a_map);
    printf("werks_kvm_loop_items b_map\n");
    werks_kvm_loop_items(b_map, map_looper);
    printf("--\n");
    printf("werks_kvm_delete_not_prefixed_items b_map\n");
    werks_kvm_delete_not_prefixed_items(b_map, "num");
    Tests.run("werks_kvm_get_items_count b_map 1", werks_kvm_get_items_count(b_map) == 1);
    printf("werks_kvm_delete_not_suffixed_items b_map\n");
    werks_kvm_delete_not_suffixed_items(b_map, "something");
    Tests.run("werks_kvm_get_items_count b_map 0", werks_kvm_get_items_count(b_map) == 0);
    printf("werks_kvm_loop_items b_map\n");
    werks_kvm_loop_items(b_map, map_looper);
    printf("--\n");
    werks_kvm_destroy(b_map);
    werks_kvm_dt* m_map = werks_kvm_load_from_string("str1=(string)Hello\nstr2=(string)World\nnum=(short)123");
    Tests.run("werks_kvm_get_items_count m_map 3", werks_kvm_get_items_count(m_map) == 3);
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(m_map, "blah"));
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(m_map, "other"));
    werks_kvm_dt* n_map = werks_kvm_load_from_string("str1=(string)Hello\nstr2=(string)World\nblah=(long)456\nother=(int)789");
    Tests.run("werks_kvm_include_items m_map n_map", werks_kvm_include_items(m_map, n_map));
    Tests.run("werks_kvm_get_items_count m_map 5", werks_kvm_get_items_count(m_map) == 5);
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(m_map, "blah"));
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(m_map, "other"));
    werks_kvm_clear(n_map);
    werks_kvm_dt* o_map = werks_kvm_load_from_string("blah=(long)111\nother=(short)222");
    werks_kvm_dt* p_map = werks_kvm_clone(m_map);
    werks_kvm_dt* q_map = werks_kvm_clone(m_map);
    Tests.run("werks_kvm_exclude_typed_items_of m_map o_map", werks_kvm_exclude_typed_items_of(m_map, o_map));
    Tests.run("werks_kvm_get_items_count m_map 4", werks_kvm_get_items_count(m_map) == 4);
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(m_map, "blah"));
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(m_map, "other"));
    Tests.run("werks_kvm_exclude_items_of m_map o_map", werks_kvm_exclude_items_of(m_map, o_map));
    Tests.run("werks_kvm_get_items_count m_map 3", werks_kvm_get_items_count(m_map) == 3);
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(m_map, "blah"));
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(m_map, "other"));
    Tests.run("werks_kvm_keep_typed_items_of m_map o_map", werks_kvm_keep_typed_items_of(p_map, o_map));
    Tests.run("werks_kvm_get_items_count m_map 1", werks_kvm_get_items_count(p_map) == 1);
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(p_map, "blah"));
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(p_map, "other"));
    Tests.run("werks_kvm_keep_items_of m_map o_map", werks_kvm_keep_items_of(q_map, o_map));
    Tests.run("werks_kvm_get_items_count m_map 2", werks_kvm_get_items_count(q_map) == 2);
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(q_map, "blah"));
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(q_map, "other"));
    ssize_t sz1;
    __auto const char** out_keys_arr_with_sz = werks_kvm_keys_to_array_with_size(q_map, &sz1);
    Tests.run("werks_kvm_keys_to_array_with_size q_map", string_array_contains(sz1, out_keys_arr_with_sz, "blah") && sz1 == 2);
    Tests.print("size: %ld\n", sz1);
    Tests.print("find: %s\n", strbool(string_array_contains(sz1, out_keys_arr_with_sz, "blah")));
    sz1 = 0;
    char** out_keys_sorted_arr_with_sz = werks_kvm_get_keys_as_sorted_array_with_size(q_map, &sz1);
    Tests.run("werks_kvm_get_keys_to_sorted_array_with_sentinel q_map", streq(out_keys_sorted_arr_with_sz[0], "blah") && streq(out_keys_sorted_arr_with_sz[1], "other") && sz1 == 2);
    string_array_destroy(out_keys_sorted_arr_with_sz, sz1);
    __auto const char** out_keys_arr_with_sentinel = werks_kvm_keys_to_array_with_sentinel(q_map);
    ssize_t sz2 = string_array_find_null_sentinel(out_keys_arr_with_sentinel, werks_kvm_get_items_count(q_map) + 1);
    Tests.run("werks_kvm_keys_to_array_with_sentinel q_map", string_array_contains(sz2, out_keys_arr_with_sentinel, "blah") && sz2 == 2);
    Tests.print("size: %ld\n", sz2);
    Tests.print("find: %s\n", strbool(string_array_contains(sz2, out_keys_arr_with_sentinel, "blah")));
    char** out_keys_sorted_arr_with_sentinel = werks_kvm_get_keys_as_sorted_array_with_sentinel(q_map);
    Tests.run("werks_kvm_get_keys_to_sorted_array_with_sentinel q_map", streq(out_keys_sorted_arr_with_sentinel[0], "blah") && streq(out_keys_sorted_arr_with_sentinel[1], "other"));
    string_array_destroy(out_keys_sorted_arr_with_sentinel, string_array_find_null_sentinel((const char**)out_keys_sorted_arr_with_sentinel, 42));
    werks_kvm_destroy(o_map);
    werks_kvm_destroy(p_map);
    werks_kvm_destroy(q_map);
    Tests.run("werks_kvm_copy_not_typed_items m_map n_map", werks_kvm_copy_not_typed_items(m_map, WERKS_KVM_TYPE_STRING, n_map));
    Tests.run("werks_kvm_get_items_count n_map 1", werks_kvm_get_items_count(n_map) == 1);
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(n_map, "num"));
    werks_kvm_clear(n_map);
    Tests.run("werks_kvm_copy_not_prefixed_items m_map n_map", werks_kvm_copy_not_prefixed_items(m_map, "str", n_map));
    Tests.run("werks_kvm_get_items_count n_map 1", werks_kvm_get_items_count(n_map) == 1);
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(n_map, "num"));
    werks_kvm_clear(n_map);
    Tests.run("werks_kvm_copy_not_suffixed_items m_map n_map", werks_kvm_copy_not_suffixed_items(m_map, "num", n_map));
    Tests.run("werks_kvm_get_items_count n_map 2", werks_kvm_get_items_count(n_map) == 2);
    Tests.run("werks_kvm_has_item NO", !werks_kvm_has_item(n_map, "num"));
    Tests.run("werks_kvm_has_items_prefixed YES", werks_kvm_has_items_prefixed(n_map, "str"));
    werks_kvm_clear(n_map);
    Tests.run("werks_kvm_transfer_not_typed_items m_map n_map", werks_kvm_transfer_not_typed_items(m_map, WERKS_KVM_TYPE_STRING, n_map));
    Tests.run("werks_kvm_get_items_count m_map 2", werks_kvm_get_items_count(m_map) == 2);
    Tests.run("werks_kvm_get_items_count n_map 1", werks_kvm_get_items_count(n_map) == 1);
    Tests.run("werks_kvm_has_item YES", werks_kvm_has_item(n_map, "num"));
    Tests.run("werks_kvm_transfer_not_prefixed_items n_map m_map", werks_kvm_transfer_not_prefixed_items(n_map, "str", m_map));
    Tests.run("werks_kvm_get_items_count m_map 3", werks_kvm_get_items_count(m_map) == 3);
    Tests.run("werks_kvm_get_items_count n_map 0", werks_kvm_get_items_count(n_map) == 0);
    Tests.run("werks_kvm_has_items_prefixed YES", werks_kvm_has_items_prefixed(m_map, "str"));
    Tests.run("werks_kvm_transfer_not_suffixed_items m_map n_map", werks_kvm_transfer_not_suffixed_items(m_map, "num", n_map));
    Tests.run("werks_kvm_get_items_count m_map 1", werks_kvm_get_items_count(m_map) == 1);
    Tests.run("werks_kvm_get_items_count n_map 2", werks_kvm_get_items_count(n_map) == 2);
    Tests.run("werks_kvm_has_items_prefixed YES", werks_kvm_has_items_prefixed(n_map, "str"));
    werks_kvm_destroy(n_map);
    werks_kvm_dt* u_map = werks_kvm_make();
    Tests.run("werks_kvm_get_eol_replacement u_map", streq(werks_kvm_get_eol_replacement(u_map), "\\n"));
    werks_kvm_set_eol_replacement(u_map, "###");
    Tests.run("werks_kvm_get_eol_replacement u_map", streq(werks_kvm_get_eol_replacement(u_map), "###"));
    werks_kvm_set_string(u_map, "string", "test\ntesting");
    Tests.print("%s\n", werks_kvm_get_string(u_map, "string"));
    __auto char* saved = werks_kvm_save_to_string(u_map);
    Tests.print("-|||||||||||||||||||||||||||||-\n%s\n-|||||||||||||||||||||||||||||-\n", saved);
    werks_kvm_clear(u_map);
    werks_kvm_read_from_string(u_map, saved);
    Tests.print("%s\n", werks_kvm_get_string(u_map, "string"));
    __auto char* saved2 = werks_kvm_save_to_string(u_map);
    Tests.print("-|||||||||||||||||||||||||||||-\n%s\n-|||||||||||||||||||||||||||||-\n", saved2);
    werks_kvm_set_string(u_map, "string2", "anoter\ntest");
    werks_kvm_set_double(u_map, "dbl", 123.456);
    werks_kvm_set_kvm(u_map, "m_map");
    werks_kvm_set_float(u_map, "flt", 123.456f);
    werks_kvm_set_bool(m_map, "bln", true);
    werks_kvm_read_items(werks_kvm_get_kvm(u_map, "m_map"), m_map);
    werks_kvm_clear(m_map);
    werks_kvm_set_kvm(u_map, "cleared");
    werks_kvm_read_items(werks_kvm_get_kvm(u_map, "cleared"), m_map);
    __auto char* saved3 = werks_kvm_export_to_json_object_string(u_map);
    Tests.print("-|||||||||||||||||||||||||||||-\n%s\n-|||||||||||||||||||||||||||||-\n", saved3);
    werks_kvm_disable_persistence(werks_kvm_get_kvm(u_map, "cleared"));
    __auto char* saved4 = werks_kvm_export_to_json_object_string(u_map);
    Tests.print("-|||||||||||||||||||||||||||||-\n%s\n-|||||||||||||||||||||||||||||-\n", saved4);
    werks_kvm_destroy(u_map);
    werks_kvm_destroy(m_map);
    return Tests.end();
}

