#include "gem_testing.h"
#include "werks_stringlist.h"

#ifdef WERKS_HELP
CE_MESSAGE("compile with: -Wall -Wfatal-errors -I../include -I../src -o ../bin/werks_stringlist_test ../src/kewl.c ../src/werks_stringlist.c werks_stringlist_test.c");
#endif

void loop_handler(werks_stringlist_dt* l, ssize_t index, const char* item) {
    Tests.print("[%p:%d] %s\n", l, index, item);
}

char* treat_handler(__unused werks_stringlist_dt* l, __unused ssize_t index, const char* item) {
    return (char*)item;
}

void loop_with_reference_handler(werks_stringlist_dt* l, ssize_t index, const char* item, void* ref) {
    Tests.print("[%p:%d] %s (%p)\n", l, index, item, ref);
}

char* treat_with_reference_handler(__unused werks_stringlist_dt* l, __unused ssize_t index, const char* item, __unused void* ref) {
    return (char*)item;
}

bool on_before_write_to_file(__unused werks_stringlist_dt* l, const char* filename) {
    Tests.print("%s\n", filename);
    return false;
}

bool on_before_read_from_file(__unused werks_stringlist_dt* l, const char* filename) {
    Tests.print("%s\n", filename);
    return false;
}

int main(void) {
    Tests.begin("WeRKS STRINGLIST");
    werks_stringlist_dt* sl = werks_stringlist_make();
    Tests.run("werks_stringlist_make", sl != NULL);
    Tests.run("werks_stringlist_get_component", assigned(werks_stringlist_get_component(sl)));
    Tests.run("werks_stringlist_get_capacity == WERKS_STRINGLIST_INITIAL_CAPACITY", werks_stringlist_get_capacity(sl) == WERKS_STRINGLIST_INITIAL_CAPACITY);
    Tests.print("capacity %d\n", werks_stringlist_get_capacity(sl));
    Tests.run("werks_stringlist_grow_capacity MANUAL", werks_stringlist_grow_capacity(sl, 1.5, 0.5));
    Tests.print("capacity %d\n", werks_stringlist_get_capacity(sl));
    Tests.run("werks_stringlist_grow_capacity 0.0 0.0", werks_stringlist_grow_capacity(sl, 0.0, 0.0));
    Tests.print("capacity %d\n", werks_stringlist_get_capacity(sl));
    werks_stringlist_destroy(sl);
    sl = werks_stringlist_create(4);
    Tests.run("werks_stringlist_create", sl != NULL);
    Tests.run("werks_stringlist_get_size NULL", werks_stringlist_get_size(NULL) == 0);
    Tests.run("werks_stringlist_get_size == 0", werks_stringlist_get_size(sl) == 0);
    Tests.run("werks_stringlist_append lit_str", werks_stringlist_append(sl, "literal"));
    Tests.run("werks_stringlist_get_size == 1", werks_stringlist_get_size(sl) == 1);
    char* data_segment_string = "ds_str";
    Tests.run("werks_stringlist_append ds_str", werks_stringlist_append(sl, data_segment_string));
    Tests.run("werks_stringlist_get_size == 2", werks_stringlist_get_size(sl) == 2);
    char stack_string[] = "stk_str";
    Tests.run("werks_stringlist_append stk_str", werks_stringlist_append(sl, stack_string));
    Tests.run("werks_stringlist_get_size == 3", werks_stringlist_get_size(sl) == 3);
    char* heap_string = malloc(5);
    strcpy(heap_string, "heap\0");
    Tests.run("werks_stringlist_append heap_str", werks_stringlist_append(sl, heap_string));
    Tests.run("werks_stringlist_get_size == 4", werks_stringlist_get_size(sl) == 4);
    Tests.run("werks_stringlist_index_of ds_str", werks_stringlist_index_of(sl, data_segment_string) == 1);
    Tests.run("werks_stringlist_index_of inexistent", werks_stringlist_index_of(sl, "inexistent") == -1);
    Tests.run("werks_stringlist_index_of NULL", werks_stringlist_index_of(sl, NULL) == -1);
    Tests.run("werks_stringlist_get 1", streq(werks_stringlist_get(sl, 1), data_segment_string));
    Tests.run("werks_stringlist_get 11", werks_stringlist_get(sl, 11) == NULL);
    Tests.run("werks_stringlist_get -1", werks_stringlist_get(sl, -1) == NULL);
    Tests.run("werks_stringlist_set 3 lit2", werks_stringlist_set(sl, 3, "literal2"));
    Tests.run("werks_stringlist_get 3", streq(werks_stringlist_get(sl, 3), "literal2"));
    Tests.run("werks_stringlist_set 3 heap_str", werks_stringlist_set(sl, 3, heap_string));
    Tests.print("capacity: %d\n", werks_stringlist_get_capacity(sl));
    Tests.run("werks_stringlist_insert lit3 2", werks_stringlist_insert(sl, "literal3", 2));
    Tests.print("capacity: %d\n", werks_stringlist_get_capacity(sl));
    Tests.run("werks_stringlist_has", werks_stringlist_has(sl, "literal3"));
    Tests.run("werks_stringlist_get 2", streq(werks_stringlist_get(sl, 2), "literal3"));
    Tests.run("werks_stringlist_get_size == 5", werks_stringlist_get_size(sl) == 5);
    Tests.run("werks_stringlist_insert lit4 6", !werks_stringlist_insert(sl, "literal4", 6));
    Tests.run("werks_stringlist_insert lit4 5", werks_stringlist_insert(sl, "literal4", 5));
    Tests.run("werks_stringlist_get_size == 6", werks_stringlist_get_size(sl) == 6);
    Tests.run("werks_stringlist_get 5", streq(werks_stringlist_get(sl, 5), "literal4"));
    Tests.run("werks_stringlist_delete 5", werks_stringlist_delete(sl, 5));
    Tests.run("werks_stringlist_get_size == 5", werks_stringlist_get_size(sl) == 5);
    char* consolidated = werks_stringlist_consolidate(sl);
    Tests.run("werks_stringlist_consolidate", assigned(consolidated));
    Tests.print("consolidated: %s\n", consolidated);
    free(consolidated);
    char* joined = werks_stringlist_join(sl, ";");
    Tests.run("werks_stringlist_join", assigned(joined));
    Tests.print("joined: %s\n", joined);
    werks_stringlist_dt* slsp = werks_stringlist_split(joined, ";");
    free(joined);
    Tests.run("werks_stringlist_get_size slsp == 5", werks_stringlist_get_size(slsp) == 5);

    Tests.print("werks_stringlist_loop:\n");
    werks_stringlist_loop(slsp, loop_handler);
    Tests.print("werks_stringlist_reverse_loop:\n");
    werks_stringlist_reverse_loop(slsp, loop_handler);
    Tests.print("werks_stringlist_treat:\n");
    werks_stringlist_treat(slsp, treat_handler);
    Tests.print("werks_stringlist_reverse_treat:\n");
    werks_stringlist_reverse_treat(slsp, treat_handler);
#if defined(__GNUC__) && !defined(__clang__)
    Tests.print("werks_stringlist_each:\n");
    werks_stringlist_each(slsp, item, {
        Tests.print("%s\n", item);
    });
    Tests.print("werks_stringlist_meach:\n");
    werks_stringlist_meach(slsp, item, {
        return (char*)item;
    });
#endif
    Tests.print("werks_stringlist_loop_from_to:\n");
    werks_stringlist_loop_from_to(slsp, 1, 3, loop_handler);
    werks_stringlist_loop_from_to(slsp, 1, 3, loop_handler);
    werks_stringlist_loop_from_to(slsp, -1, 3, loop_handler);
    werks_stringlist_loop_from_to(slsp, 1, -3, loop_handler);
    werks_stringlist_loop_from_to(slsp, 1, 3, NULL);
    werks_stringlist_loop_from_to(NULL, 1, 3, loop_handler);
    Tests.print("werks_stringlist_reverse_loop_from_to:\n");
    werks_stringlist_reverse_loop_from_to(slsp, 1, 3, loop_handler);
    werks_stringlist_reverse_loop_from_to(slsp, -1, 3, loop_handler);
    werks_stringlist_reverse_loop_from_to(slsp, 1, -3, loop_handler);
    werks_stringlist_reverse_loop_from_to(slsp, 1, 3, NULL);
    werks_stringlist_reverse_loop_from_to(NULL, 1, 3, loop_handler);

    Tests.print("werks_stringlist_loop_with_reference:\n");
    werks_stringlist_loop_with_reference(slsp, loop_with_reference_handler, slsp);
    Tests.print("werks_stringlist_reverse_loop_with_reference:\n");
    werks_stringlist_reverse_loop_with_reference(slsp, loop_with_reference_handler, slsp);
    Tests.print("werks_stringlist_treat_with_reference:\n");
    werks_stringlist_treat_with_reference(slsp, treat_with_reference_handler, slsp);
    Tests.print("werks_stringlist_reverse_treat_with_reference:\n");
    werks_stringlist_reverse_treat_with_reference(slsp, treat_with_reference_handler, slsp);
#if defined(__GNUC__) && !defined(__clang__)
    Tests.print("werks_stringlist_each_with_reference:\n");
    werks_stringlist_each_with_reference(slsp, item, r, {
        Tests.print("%s (%p)\n", item, r);
    }, slsp);
    Tests.print("werks_stringlist_meach_with_reference:\n");
    werks_stringlist_meach_with_reference(slsp, item, r, {
        return (char*)item;
    }, slsp);
#endif
    Tests.print("werks_stringlist_loop_from_to_with_reference:\n");
    werks_stringlist_loop_from_to_with_reference(slsp, 1, 3, loop_with_reference_handler, slsp);
    werks_stringlist_loop_from_to_with_reference(slsp, -1, 3, loop_with_reference_handler, slsp);
    werks_stringlist_loop_from_to_with_reference(slsp, 1, -3, loop_with_reference_handler, slsp);
    werks_stringlist_loop_from_to_with_reference(slsp, 1, 3, NULL, slsp);
    werks_stringlist_loop_from_to_with_reference(NULL, 1, 3, loop_with_reference_handler, slsp);
    Tests.print("werks_stringlist_reverse_loop_from_to_with_reference:\n");
    werks_stringlist_reverse_loop_from_to_with_reference(slsp, 1, 3, loop_with_reference_handler, slsp);
    werks_stringlist_reverse_loop_from_to_with_reference(slsp, -1, 3, loop_with_reference_handler, slsp);
    werks_stringlist_reverse_loop_from_to_with_reference(slsp, 1, -3, loop_with_reference_handler, slsp);
    werks_stringlist_reverse_loop_from_to_with_reference(slsp, 1, 3, NULL, slsp);
    werks_stringlist_reverse_loop_from_to_with_reference(NULL, 1, 3, loop_with_reference_handler, slsp);
    
    Tests.run("werks_stringlist_get_on_before_write_to_file slsp", werks_stringlist_get_on_before_write_to_file(slsp) == NULL);
    werks_stringlist_set_on_before_write_to_file(slsp, on_before_write_to_file);
    Tests.run("werks_stringlist_set_on_before_write_to_file slsp", werks_stringlist_get_on_before_write_to_file(slsp) != NULL);
    Tests.run("werks_stringlist_save_to_file slsp NO", !werks_stringlist_save_to_file(slsp, "sltest.txt"));
    werks_stringlist_set_on_before_write_to_file(slsp, NULL);
    Tests.run("werks_stringlist_save_to_file slsp YES", werks_stringlist_save_to_file(slsp, "sltest.txt"));
    werks_stringlist_dt* sltmp = werks_stringlist_make();
    Tests.run("werks_stringlist_get_on_before_read_from_file sltmp", werks_stringlist_get_on_before_read_from_file(sltmp) == NULL);
    werks_stringlist_set_on_before_read_from_file(sltmp, on_before_read_from_file);
    Tests.run("werks_stringlist_set_on_before_read_from_file sltmp", werks_stringlist_get_on_before_read_from_file(sltmp) != NULL);
    Tests.run("werks_stringlist_load_from_file sltmp NO", !werks_stringlist_read_from_file(sltmp, "sltest.txt"));
    werks_stringlist_set_on_before_read_from_file(sltmp, NULL);
    Tests.run("werks_stringlist_load_from_file sltmp YES", werks_stringlist_read_from_file(sltmp, "sltest.txt"));
    Tests.run("werks_stringlist_get_size sltmp == 5", werks_stringlist_get_size(sltmp) == 5);
    werks_stringlist_destroy(sltmp);
    werks_stringlist_dt* slts = werks_stringlist_load_from_file("sltest.txt");
    Tests.run("werks_stringlist_load_from_file", assigned(slts));
    Tests.run("werks_stringlist_get_size slts == 5", werks_stringlist_get_size(slts) == 5);
    werks_stringlist_destroy(slts);
    Tests.run("werks_stringlist_append_to_file", werks_stringlist_append_to_file(slsp, "sltest.txt"));
    werks_stringlist_dt* slts2 = werks_stringlist_load_from_file("sltest.txt");
    Tests.run("werks_stringlist_load_from_file", assigned(slts));
    Tests.run("werks_stringlist_get_size slts2 == 10", werks_stringlist_get_size(slts2) == 10);
    //Tests.print("%ld", werks_stringlist_get_capacity(slts2));
    Tests.run("werks_stringlist_has_duplicates slts2", werks_stringlist_has_duplicates(slts2));
    Tests.run("werks_stringlist_count_duplicates slts2 5", werks_stringlist_count_duplicates(slts2) == 5);
    werks_stringlist_dt* sldups = werks_stringlist_list_duplicates(slts2);
    Tests.run("werks_stringlist_list_duplicates sldups", assigned(sldups));
    Tests.run("werks_stringlist_get_size sldups == 5", werks_stringlist_get_size(sldups) == 5);
    werks_stringlist_destroy(sldups);
    Tests.run("werks_stringlist_last_index_of slts2 ds_str", werks_stringlist_last_index_of(slts2, data_segment_string) == 6);
    Tests.run("werks_stringlist_last_index_of slts2 inexistent", werks_stringlist_last_index_of(slts2, "inexistent") == -1);
    Tests.run("werks_stringlist_last_index_of slts2 NULL", werks_stringlist_last_index_of(slts2, NULL) == -1);
    Tests.run("werks_stringlist_remove_duplicates slts2", werks_stringlist_remove_duplicates(slts2));
    Tests.run("werks_stringlist_count_duplicates slts2 0", werks_stringlist_count_duplicates(slts2) == 0);
    werks_stringlist_destroy(slts2);
    remove("sltest.txt");
    Tests.run("werks_stringlist_has_duplicates slsp", !werks_stringlist_has_duplicates(slsp));
    werks_stringlist_destroy(slsp);

    werks_stringlist_dt* sl2 = werks_stringlist_clone(sl);
    Tests.run("werks_stringlist_clone", werks_stringlist_get_size(sl2) == 5);
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.print("sl2[3] = %s\n", werks_stringlist_get(sl2, 3));
    Tests.print("sl2[4] = %s\n", werks_stringlist_get(sl2, 4));
    char* tmp = werks_stringlist_take(sl, 2);
    Tests.run("werks_stringlist_take 2", streq(tmp, "literal3"));
    free(tmp);
    Tests.run("werks_stringlist_get_size == 4", werks_stringlist_get_size(sl) == 4);
    Tests.run("werks_stringlist_remove_once heap_str", werks_stringlist_remove_once(sl, heap_string));
    Tests.run("werks_stringlist_get_size == 3", werks_stringlist_get_size(sl) == 3);
    Tests.run("werks_stringlist_remove_once stk_str", werks_stringlist_remove_once(sl, stack_string));
    Tests.run("werks_stringlist_get_size == 2", werks_stringlist_get_size(sl) == 2);
    Tests.run("werks_stringlist_remove_once ds_str", werks_stringlist_remove_once(sl, data_segment_string));
    Tests.run("werks_stringlist_get_size == 1", werks_stringlist_get_size(sl) == 1);
    Tests.run("werks_stringlist_remove_once lit_str", werks_stringlist_remove_once(sl, "literal"));
    Tests.run("werks_stringlist_get_size == 0", werks_stringlist_get_size(sl) == 0);
    Tests.run("werks_stringlist_remove_once inexistent", !werks_stringlist_remove_once(sl, "inexistent"));
    Tests.run("werks_stringlist_remove_once NULL", !werks_stringlist_remove_once(sl, NULL));
    Tests.run("werks_stringlist_get sl2 0", streq(werks_stringlist_get(sl2, 0), "literal"));
    Tests.run("werks_stringlist_get sl2 4", streq(werks_stringlist_get(sl2, 4), heap_string));
    Tests.run("werks_stringlist_get_size sl2 == 5", werks_stringlist_get_size(sl2) == 5);
    werks_stringlist_destroy(sl);

    Tests.run("werks_stringlist_reverse sl2", werks_stringlist_reverse(sl2));
    Tests.run("werks_stringlist_get_size sl2 == 5", werks_stringlist_get_size(sl2) == 5);
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.print("sl2[3] = %s\n", werks_stringlist_get(sl2, 3));
    Tests.print("sl2[4] = %s\n", werks_stringlist_get(sl2, 4));
    const char* n4 = werks_stringlist_get(sl2, 4);
    Tests.run("werks_stringlist_get sl2 4", streq(n4, "literal"));
    Tests.print("%s\n", n4);
    const char* n0 = werks_stringlist_get(sl2, 0);
    Tests.run("werks_stringlist_get sl2 0", streq(n0, heap_string));
    Tests.print("%s\n", n0);
    Tests.run("werks_stringlist_set sl2 4", werks_stringlist_set(sl2, 4, "new literal"));
    const char* nl4 = werks_stringlist_get(sl2, 4);
    Tests.print("%s\n", nl4);
    Tests.run("werks_stringlist_get sl2 4", streq(nl4, "new literal"));
    Tests.run("werks_stringlist_swap sl2 0 4", werks_stringlist_swap(sl2, 0, 4));
    Tests.print("[0] %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("[4] %s\n", werks_stringlist_get(sl2, 4));
    char* t4 = werks_stringlist_take_last(sl2);
    Tests.run("werks_stringlist_take_last sl2", streq(t4, "heap"));
    free(t4);
    Tests.run("werks_stringlist_get_size sl2 == 4", werks_stringlist_get_size(sl2) == 4);
    Tests.run("werks_stringlist_delete_last sl2", werks_stringlist_delete_last(sl2));
    Tests.run("werks_stringlist_get_size sl2 == 3", werks_stringlist_get_size(sl2) == 3);
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.run("werks_stringlist_format sl2 2 []", werks_stringlist_format(sl2, 2, "[%s]"));
    Tests.run("werks_stringlist_format sl2 2 [] ?", streq(werks_stringlist_get(sl2, 2), "[literal3]"));
    Tests.run("werks_stringlist_format_all sl2 <>", werks_stringlist_format_all(sl2, "<%s>") &&
        ('<' == werks_stringlist_get(sl2, 0)[0]) &&
        (werks_stringlist_get(sl2, 0)[0] == werks_stringlist_get(sl2, 1)[0]) &&
        (werks_stringlist_get(sl2, 1)[0] == werks_stringlist_get(sl2, 2)[0])
    );
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.run("werks_stringlist_count_prefixed sl2 __ 0", werks_stringlist_count_prefixed(sl2, "__") == 0);
    Tests.run("werks_stringlist_prefix sl2 2 __", werks_stringlist_prefix(sl2, 2, "__"));
    Tests.run("werks_stringlist_count_prefixed sl2 __ 1", werks_stringlist_count_prefixed(sl2, "__") == 1);
    Tests.print("werks_stringlist_loop_prefixed:\n");
    werks_stringlist_loop_prefixed(sl2, "__", loop_handler);
    Tests.print("werks_stringlist_reverse_loop_prefixed:\n");
    werks_stringlist_reverse_loop_prefixed(sl2, "__", loop_handler);
    Tests.print("werks_stringlist_loop_prefixed_with_reference:\n");
    werks_stringlist_loop_prefixed_with_reference(sl2, "__", loop_with_reference_handler, sl2);
    Tests.print("werks_stringlist_reverse_loop_prefixed_with_reference:\n");
    werks_stringlist_reverse_loop_prefixed_with_reference(sl2, "__", loop_with_reference_handler, sl2);
    Tests.run("werks_stringlist_prefix sl2 2 __ ?", streq(werks_stringlist_get(sl2, 2), "__<[literal3]>"));
    Tests.run("werks_stringlist_count_suffixed sl2 __ 0", werks_stringlist_count_suffixed(sl2, "__") == 0);
    Tests.run("werks_stringlist_suffix sl2 2 __", werks_stringlist_suffix(sl2, 2, "__"));
    Tests.run("werks_stringlist_count_suffixed sl2 __ 1", werks_stringlist_count_suffixed(sl2, "__") == 1);
    Tests.print("werks_stringlist_loop_suffixed:\n");
    werks_stringlist_loop_suffixed(sl2, "__", loop_handler);
    Tests.print("werks_stringlist_reverse_loop_suffixed:\n");
    werks_stringlist_reverse_loop_suffixed(sl2, "__", loop_handler);
    Tests.print("werks_stringlist_loop_suffixed_with_reference:\n");
    werks_stringlist_loop_suffixed_with_reference(sl2, "__", loop_with_reference_handler, sl2);
    Tests.print("werks_stringlist_reverse_loop_suffixed_with_reference:\n");
    werks_stringlist_reverse_loop_suffixed_with_reference(sl2, "__", loop_with_reference_handler, sl2);
    Tests.run("werks_stringlist_suffix sl2 2 __ ?", streq(werks_stringlist_get(sl2, 2), "__<[literal3]>__"));
    Tests.run("werks_stringlist_count_occurrences sl2 1", werks_stringlist_count_occurrences(sl2, "__<[literal3]>__") == 1);
    Tests.run("werks_stringlist_set sl2 2 back", werks_stringlist_set(sl2, 2, "<[literal3]>"));
    Tests.run("werks_stringlist_count_occurrences sl2 0", werks_stringlist_count_occurrences(sl2, "__<[literal3]>__") == 0);
    Tests.run("werks_stringlist_move_first sl2 2", werks_stringlist_move_first(sl2, 2));
    Tests.run("werks_stringlist_move_first sl2 2 ?", streq(werks_stringlist_get(sl2, 0), "<[literal3]>"));
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.run("werks_stringlist_move_last sl2 1", werks_stringlist_move_last(sl2, 1));
    Tests.run("werks_stringlist_move_last sl2 1 ?", streq(werks_stringlist_get(sl2, 2), "<new literal>"));
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.run("werks_stringlist_move_down sl2 1", werks_stringlist_move_down(sl2, 1));
    Tests.run("werks_stringlist_move_down sl2 1 ?", streq(werks_stringlist_get(sl2, 2), "<stk_str>"));
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.run("werks_stringlist_move_up sl2 2", werks_stringlist_move_up(sl2, 2));
    Tests.run("werks_stringlist_move_up sl2 2 ?", streq(werks_stringlist_get(sl2, 1), "<stk_str>"));
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));

    Tests.run("werks_stringlist_split NULL sep", werks_stringlist_split(NULL, ";") == NULL);
    Tests.run("werks_stringlist_split NULL val", werks_stringlist_split("abc;def;ghi", NULL) == NULL);
    werks_stringlist_dt* sl3 = werks_stringlist_split("abc;def;ghi", ";");
    Tests.run("werks_stringlist_split sl3", werks_stringlist_get_size(sl3) == 3);
    Tests.print("sl3[0] = %s\n", werks_stringlist_get(sl3, 0));
    Tests.print("sl3[1] = %s\n", werks_stringlist_get(sl3, 1));
    Tests.print("sl3[2] = %s\n", werks_stringlist_get(sl3, 2));
    Tests.print("werks_stringlist_get_capacity(sl3) = %ld\n", werks_stringlist_get_capacity(sl3));
    werks_stringlist_set_capacity_grow_factor(sl3, 1.5f);
    Tests.print("Capacity grow factor: %f\n", werks_stringlist_get_capacity_grow_factor(sl3));
    werks_stringlist_set_capacity_grow_padding(sl3, 0.5f);
    Tests.print("Capacity grow padding: %f\n", werks_stringlist_get_capacity_grow_padding(sl3));
    werks_stringlist_prepend_all(sl2, sl3);
    Tests.run("werks_stringlist_prepend_all sl2 sl", werks_stringlist_get_size(sl2) == 6 && streq(werks_stringlist_get(sl2, 0), "abc"));
    Tests.print("werks_stringlist_get_size(sl2) = %ld\n", werks_stringlist_get_size(sl2));
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.print("sl2[3] = %s\n", werks_stringlist_get(sl2, 3));
    Tests.print("sl2[4] = %s\n", werks_stringlist_get(sl2, 4));
    Tests.print("sl2[5] = %s\n", werks_stringlist_get(sl2, 5));
    Tests.run("werks_stringlist_prepend_all sl2 sl2", !werks_stringlist_prepend_all(sl2, sl2));
    Tests.run("werks_stringlist_get_size sl2 6", werks_stringlist_get_size(sl2) == 6);
    werks_stringlist_append_all(sl2, sl3);
    Tests.run("werks_stringlist_append_all sl2 sl", werks_stringlist_get_size(sl2) == 9 && streq(werks_stringlist_get(sl2, 8), "ghi"));
    Tests.print("werks_stringlist_get_size(sl2) = %ld\n", werks_stringlist_get_size(sl2));
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl2, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl2, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl2, 2));
    Tests.print("sl2[3] = %s\n", werks_stringlist_get(sl2, 3));
    Tests.print("sl2[4] = %s\n", werks_stringlist_get(sl2, 4));
    Tests.print("sl2[5] = %s\n", werks_stringlist_get(sl2, 5));
    Tests.print("sl2[6] = %s\n", werks_stringlist_get(sl2, 6));
    Tests.print("sl2[7] = %s\n", werks_stringlist_get(sl2, 7));
    Tests.print("sl2[8] = %s\n", werks_stringlist_get(sl2, 8));
    Tests.run("werks_stringlist_append_all sl2 sl2", !werks_stringlist_append_all(sl2, sl2));
    Tests.run("werks_stringlist_get_size sl2 9", werks_stringlist_get_size(sl2) == 9);
    
    Tests.run("werks_stringlist_exclude_all sl2 sl3", werks_stringlist_exclude_all(sl2, sl3));
    Tests.run("werks_stringlist_get_size sl2 3", werks_stringlist_get_size(sl2) == 3);
    Tests.run("werks_stringlist_exclude_all sl3 sl3", !werks_stringlist_exclude_all(sl3, sl3));
    Tests.run("werks_stringlist_include_all sl2 sl3", werks_stringlist_include_all(sl2, sl3));
    Tests.run("werks_stringlist_get_size sl2 6", werks_stringlist_get_size(sl2) == 6);
    Tests.run("werks_stringlist_get sl2 5 ghi", streq(werks_stringlist_get(sl2, 5), "ghi"));
    Tests.run("werks_stringlist_include_all sl3 sl3", !werks_stringlist_include_all(sl3, sl3));
    Tests.run("werks_stringlist_include sl2 test", werks_stringlist_include(sl2, "test"));
    Tests.run("werks_stringlist_get_size sl2 7", werks_stringlist_get_size(sl2) == 7);
    werks_stringlist_dt* slX = werks_stringlist_clone(sl2);
    Tests.run("werks_stringlist_get_size slX 7", werks_stringlist_get_size(slX) == 7);
    Tests.run("werks_stringlist_remove_all slX test", werks_stringlist_remove_all(slX, "test"));
    Tests.run("werks_stringlist_get_size slX 6", werks_stringlist_get_size(slX) == 6);
    Tests.run("werks_stringlist_keep_all sl2 slX", werks_stringlist_keep_all(sl2, slX));
    werks_stringlist_destroy(slX);
    Tests.run("werks_stringlist_get_size sl2 6", werks_stringlist_get_size(sl2) == 6);
    werks_stringlist_remove_all(sl2, "abc");
    Tests.run("werks_stringlist_remove_all sl2 abc", !werks_stringlist_has(sl2, "abc"));
    Tests.run("werks_stringlist_get_size sl2 5", werks_stringlist_get_size(sl2) == 5);
    Tests.run("werks_stringlist_delete sl2 0", werks_stringlist_delete(sl2, 0));
    Tests.run("werks_stringlist_get_size sl2 4", werks_stringlist_get_size(sl2) == 4);
    Tests.run("werks_stringlist_prefix_all sl2 ##", werks_stringlist_prefix_all(sl2, "##") &&
        (starts_with(werks_stringlist_get(sl2, 0), "##")) &&
        (starts_with(werks_stringlist_get(sl2, 1), "##")) &&
        (starts_with(werks_stringlist_get(sl2, 2), "##"))
    );
    werks_stringlist_dt* slY = werks_stringlist_clone(sl2);
    Tests.run("werks_stringlist_get_size slY 4", werks_stringlist_get_size(slY) == 4);
    Tests.run("werks_stringlist_remove_prefixed slY ##", werks_stringlist_remove_prefixed(slY, "##"));
    Tests.run("werks_stringlist_get_size slY 0", werks_stringlist_get_size(slY) == 0);
    werks_stringlist_destroy(slY);
    slY = werks_stringlist_clone(sl2);
    Tests.run("werks_stringlist_get_size slY 4", werks_stringlist_get_size(slY) == 4);
    Tests.run("werks_stringlist_remove_not_prefixed slY ZZ", werks_stringlist_remove_not_prefixed(slY, "ZZ"));
    Tests.run("werks_stringlist_get_size slY 0", werks_stringlist_get_size(slY) == 0);
    werks_stringlist_destroy(slY);
    slY = werks_stringlist_clone(sl2);
    Tests.run("werks_stringlist_get_size slY 4", werks_stringlist_get_size(slY) == 4);
    Tests.run("werks_stringlist_remove_not_suffixed slY ZZ", werks_stringlist_remove_not_suffixed(slY, "ZZ"));
    Tests.run("werks_stringlist_get_size slY 0", werks_stringlist_get_size(slY) == 0);
    werks_stringlist_destroy(slY);
    Tests.run("werks_stringlist_suffix_all sl2 $$", werks_stringlist_suffix_all(sl2, "$$") &&
        (ends_with(werks_stringlist_get(sl2, 0), "$$")) &&
        (ends_with(werks_stringlist_get(sl2, 1), "$$")) &&
        (ends_with(werks_stringlist_get(sl2, 2), "$$"))
    );
    Tests.run("werks_stringlist_remove_suffixed sl2 $$", werks_stringlist_remove_suffixed(sl2, "$$"));
    Tests.run("werks_stringlist_clear sl2", werks_stringlist_get_size(sl2) == 0);
    Tests.print("werks_stringlist_get_size(sl2) = %ld\n", werks_stringlist_get_size(sl2));
    Tests.run("werks_stringlist_push sl2 lit_str4", werks_stringlist_push(sl2, "literal4"));
    char* pops = werks_stringlist_pop(sl2);
    Tests.print("%s\n", pops);
    Tests.run("werks_stringlist_pop sl2 lit_str4", streq(pops, "literal4"));
    char* popn = werks_stringlist_pop(sl2);
    Tests.print("%s\n", popn);
    Tests.run("werks_stringlist_pop sl2 NULL", popn == NULL);
    free(pops);
    free(popn);
    werks_stringlist_destroy(sl2);
    werks_stringlist_destroy(sl3);
    const char* lit_arr_with_sz[] = {"Hello", "World", "!!!"};
    werks_stringlist_dt* sl4 = werks_stringlist_from_array_with_size(lit_arr_with_sz, 3);
    Tests.run("werks_stringlist_from_array_with_size sl4 lit_arr 3", werks_stringlist_get_size(sl4) == 3);
    Tests.print("sl2[0] = %s\n", werks_stringlist_get(sl4, 0));
    Tests.print("sl2[1] = %s\n", werks_stringlist_get(sl4, 1));
    Tests.print("sl2[2] = %s\n", werks_stringlist_get(sl4, 2));
    ssize_t sz;
    __auto const char** out_lit_arr_with_sz = werks_stringlist_to_array_with_size(sl4, &sz);
    Tests.run("werks_stringlist_to_array_with_size sl4", streq(out_lit_arr_with_sz[0], "Hello") && sz == 3);
    werks_stringlist_destroy(sl4);
    const char* lit_arr_w_sen[] = {"Hello", "World", "Again", "!!!", NULL};
    werks_stringlist_dt* sl5 = werks_stringlist_from_array_with_sentinel(lit_arr_w_sen);
    Tests.run("werks_stringlist_from_array_with_sentinel sl5 lit_arr_w_sen 4", werks_stringlist_get_size(sl5) == 4);
    Tests.print("sl5[0] = %s\n", werks_stringlist_get(sl5, 0));
    Tests.print("sl5[1] = %s\n", werks_stringlist_get(sl5, 1));
    Tests.print("sl5[2] = %s\n", werks_stringlist_get(sl5, 2));
    Tests.print("sl5[3] = %s\n", werks_stringlist_get(sl5, 3));
    __auto const char** out_lit_arr_with_sen = werks_stringlist_to_array_with_sentinel(sl5);
    Tests.run("werks_stringlist_to_array_with_sentinel sl5", streq(out_lit_arr_with_sen[0], "Hello") && string_array_find_null_sentinel(out_lit_arr_with_sen, WERKS_STRINGLIST_SENTINEL_LIMIT) == 4);
    werks_stringlist_dt* sl6 = werks_stringlist_from_array_with_sentinel((const char*[]){"1", "2", "3", NULL});
    Tests.run("werks_stringlist_insert_all sl5 sl6", werks_stringlist_insert_all(sl5, sl6, 2));
    Tests.run("werks_stringlist_get_size sl5 7", werks_stringlist_get_size(sl5) == 7);
    Tests.print("sl5[0] = %s\n", werks_stringlist_get(sl5, 0));
    Tests.print("sl5[1] = %s\n", werks_stringlist_get(sl5, 1));
    Tests.print("sl5[2] = %s\n", werks_stringlist_get(sl5, 2));
    Tests.print("sl5[3] = %s\n", werks_stringlist_get(sl5, 3));
    Tests.print("sl5[4] = %s\n", werks_stringlist_get(sl5, 4));
    Tests.print("sl5[5] = %s\n", werks_stringlist_get(sl5, 5));
    Tests.print("sl5[6] = %s\n", werks_stringlist_get(sl5, 6));
    Tests.run("werks_stringlist_insert_all sl5 sl5", !werks_stringlist_insert_all(sl5, sl5, 3));
    Tests.run("werks_stringlist_get_size sl5 7", werks_stringlist_get_size(sl5) == 7);
    werks_stringlist_dt* slE0 = werks_stringlist_clone(sl5);
    Tests.run("werks_stringlist_clone sl5 slE0", slE0 != NULL);
    Tests.run("werks_stringlist_get_size slE0 7", werks_stringlist_get_size(slE0) == 7);
    werks_stringlist_dt* slE1 = werks_stringlist_extract_first(slE0, 2);
    Tests.run("werks_stringlist_extract_first slE0 2 slE1", slE1 != NULL);
    Tests.run("werks_stringlist_get_size slE0 5", werks_stringlist_get_size(slE0) == 5);
    Tests.run("werks_stringlist_get_size slE1 2", werks_stringlist_get_size(slE1) == 2);
    werks_stringlist_dt* slE2 = werks_stringlist_extract_last(slE0, 2);
    Tests.run("werks_stringlist_extract_last slE0 2 slE2", slE2 != NULL);
    Tests.run("werks_stringlist_get_size slE0 3", werks_stringlist_get_size(slE0) == 3);
    Tests.run("werks_stringlist_get_size slE2 2", werks_stringlist_get_size(slE2) == 2);
    werks_stringlist_dt* slE3 = werks_stringlist_extract_last(slE0, 3);
    Tests.run("werks_stringlist_extract_last slE0 3 slE3", slE3 != NULL);
    Tests.run("werks_stringlist_get_size slE0 0", werks_stringlist_get_size(slE0) == 0);
    Tests.run("werks_stringlist_get_size slE3 3", werks_stringlist_get_size(slE3) == 3);
    werks_stringlist_dt* slE4 = werks_stringlist_extract_last(slE0, 1);
    Tests.run("werks_stringlist_extract_last slE0 1 slE4 NO", slE4 == NULL);
    slE4 = werks_stringlist_extract_last(slE3, 0);
    Tests.run("werks_stringlist_extract_last slE0 0 slE4 NO", slE4 == NULL);
    werks_stringlist_destroy(slE0);
    werks_stringlist_destroy(slE1);
    werks_stringlist_destroy(slE2);
    werks_stringlist_destroy(slE3);
    werks_stringlist_dt* sl7 = werks_stringlist_extract_from_to(sl5, 2, 5);
    Tests.run("werks_stringlist_extract_from_to sl5 2 5", sl7 != NULL);
    Tests.run("werks_stringlist_get_size sl7 4", werks_stringlist_get_size(sl7) == 4);
    Tests.print("sl7[0] = %s\n", werks_stringlist_get(sl7, 0));
    Tests.print("sl7[1] = %s\n", werks_stringlist_get(sl7, 1));
    Tests.print("sl7[2] = %s\n", werks_stringlist_get(sl7, 2));
    Tests.print("sl7[3] = %s\n", werks_stringlist_get(sl7, 3));
    Tests.run("werks_stringlist_get_size sl5 3", werks_stringlist_get_size(sl5) == 3);
    Tests.print("sl5[0] = %s\n", werks_stringlist_get(sl5, 0));
    Tests.print("sl5[1] = %s\n", werks_stringlist_get(sl5, 1));
    Tests.print("sl5[2] = %s\n", werks_stringlist_get(sl5, 2));
    werks_stringlist_sort(sl5);
    Tests.run("werks_stringlist_sort sl5", streq(werks_stringlist_get(sl5, 0), "!!!") &&
        streq(werks_stringlist_get(sl5, 1), "Hello") && streq(werks_stringlist_get(sl5, 2), "World"));
    Tests.print("sl5[0] = %s\n", werks_stringlist_get(sl5, 0));
    Tests.print("sl5[1] = %s\n", werks_stringlist_get(sl5, 1));
    Tests.print("sl5[2] = %s\n", werks_stringlist_get(sl5, 2));
    srand(1234); // good enough
    werks_stringlist_shuffle(sl5, rand);
    Tests.run("werks_stringlist_shuffle sl5", !(streq(werks_stringlist_get(sl5, 0), "!!!") &&
        streq(werks_stringlist_get(sl5, 1), "Hello") && streq(werks_stringlist_get(sl5, 2), "World")));
    Tests.print("sl5[0] = %s\n", werks_stringlist_get(sl5, 0));
    Tests.print("sl5[1] = %s\n", werks_stringlist_get(sl5, 1));
    Tests.print("sl5[2] = %s\n", werks_stringlist_get(sl5, 2));
    werks_stringlist_destroy(sl7);
    werks_stringlist_destroy(sl5);
    Tests.run("werks_stringlist_prepend sl6 0", werks_stringlist_prepend(sl6, "0"));
    Tests.run("werks_stringlist_get_size sl6 4", werks_stringlist_get_size(sl6) == 4);
    Tests.print("sl6[0] = %s\n", werks_stringlist_get(sl6, 0));
    Tests.print("sl6[1] = %s\n", werks_stringlist_get(sl6, 1));
    Tests.print("sl6[2] = %s\n", werks_stringlist_get(sl6, 2));
    Tests.print("sl6[3] = %s\n", werks_stringlist_get(sl6, 3));
    Tests.run("werks_stringlist_delete_from_to sl6 1 2", werks_stringlist_delete_from_to(sl6, 1, 2));
    Tests.run("werks_stringlist_get_size sl6 2", werks_stringlist_get_size(sl6) == 2);
    Tests.print("sl6[0] = %s\n", werks_stringlist_get(sl6, 0));
    Tests.print("sl6[1] = %s\n", werks_stringlist_get(sl6, 1));
    Tests.run("werks_stringlist_is_empty sl6 NO", !werks_stringlist_is_empty(sl6));
    werks_stringlist_clear(sl6);
    Tests.run("werks_stringlist_clear sl6", werks_stringlist_get_size(sl6) == 0);
    Tests.run("werks_stringlist_is_empty sl6 YES", werks_stringlist_is_empty(sl6));
    werks_stringlist_destroy(sl6);
    //Tests.run("werks_stringlist_destroy sl6", !werks_stringlist_is_empty(sl6)); // NOTE: it works as expected but its commented out since valgrind analysis gets confused
    free(heap_string);
    werks_stringlist_dt* sl8 = werks_stringlist_make();
    werks_stringlist_read_from_string(sl8, "000--abd--def--ghi--ghi--123--456--789--000", "--");
    Tests.run("werks_stringlist_read_from_string sl8", werks_stringlist_get_size(sl8) == 9);
    AUTO_STRING(csv, werks_stringlist_write_to_string(sl8, ';'));
    Tests.run("werks_stringlist_write_to_string sl8", streq(csv, "000;abd;def;ghi;ghi;123;456;789;000"));
    Tests.print("%s\n", csv);
    Tests.run("werks_stringlist_has_empties sl8 NO", !werks_stringlist_has_empties(sl8));
    Tests.run("werks_stringlist_count_empties sl8 0", werks_stringlist_count_empties(sl8) == 0);
    Tests.run("werks_stringlist_count_not_empties sl8 9", werks_stringlist_count_not_empties(sl8) == 9);
    werks_stringlist_prepend(sl8, STRINGS_NOTHING);
    Tests.run("werks_stringlist_has_empties sl8 YES", werks_stringlist_has_empties(sl8));
    Tests.run("werks_stringlist_count_empties sl8 1", werks_stringlist_count_empties(sl8) == 1);
    Tests.run("werks_stringlist_count_not_empties sl8 9", werks_stringlist_count_not_empties(sl8) == 9);
    werks_stringlist_append(sl8, STRINGS_NOTHING);
    Tests.run("werks_stringlist_count_empties sl8 2", werks_stringlist_count_empties(sl8) == 2);
    Tests.run("werks_stringlist_count_not_empties sl8 9", werks_stringlist_count_not_empties(sl8) == 9);
    AUTO_STRING(csv2, werks_stringlist_write_to_string(sl8, ';'));
    Tests.run("werks_stringlist_write_to_string sl8", streq(csv2, ";000;abd;def;ghi;ghi;123;456;789;000;"));
    Tests.print("%s\n", csv2);
    Tests.run("werks_stringlist_remove_empties sl8", werks_stringlist_remove_empties(sl8));
    Tests.run("werks_stringlist_count_empties sl8 0", werks_stringlist_count_empties(sl8) == 0);
    Tests.run("werks_stringlist_count_not_empties sl8 9", werks_stringlist_count_not_empties(sl8) == 9);
    Tests.run("werks_stringlist_drop_first sl8 2", werks_stringlist_drop_first(sl8, 2));
    Tests.run("werks_stringlist_drop_last sl8 2", werks_stringlist_drop_last(sl8, 2));
    AUTO_STRING(csv3, werks_stringlist_write_to_string(sl8, ';'));
    Tests.run("werks_stringlist_write_to_string sl8", streq(csv3, "def;ghi;ghi;123;456"));
    Tests.print("%s\n", csv3);
    werks_stringlist_destroy(sl8);
    werks_stringlist_dt* sl9 = werks_stringlist_make();
    Tests.run("werks_stringlist_is_frozen sl9", !werks_stringlist_is_frozen(sl9));
    werks_stringlist_freeze(sl9);
    Tests.run("werks_stringlist_freeze sl9", werks_stringlist_is_frozen(sl9));
    werks_stringlist_unfreeze(sl9);
    Tests.run("werks_stringlist_unfreeze sl9", !werks_stringlist_is_frozen(sl9));
    Tests.run("werks_stringlist_append sl9 literal YES", werks_stringlist_append(sl9, "literal"));
    Tests.run("werks_stringlist_append sl9 empty YES", werks_stringlist_append(sl9, ""));
    Tests.run("werks_stringlist_count_empties sl9 1", werks_stringlist_count_empties(sl9) == 1);
    Tests.run("werks_stringlist_append sl9 literal YES", werks_stringlist_append(sl9, "literal"));
    Tests.run("werks_stringlist_count_duplicates sl9 1", werks_stringlist_count_duplicates(sl9) == 1);
    Tests.run("werks_stringlist_get_size sl9 3", werks_stringlist_get_size(sl9) == 3);
    werks_stringlist_freeze(sl9);
    Tests.run("werks_stringlist_freeze sl9", werks_stringlist_is_frozen(sl9));
    Tests.run("werks_stringlist_append sl9 literal2 NO", !werks_stringlist_append(sl9, "literal2"));
    Tests.run("werks_stringlist_prepend sl9 pre empty NO", !werks_stringlist_prepend(sl9, ""));
    Tests.run("werks_stringlist_insert sl9 literal2 NO", !werks_stringlist_insert(sl9, "literal2", 2));
    Tests.run("werks_stringlist_take sl9 0 NO", werks_stringlist_take(sl9, 0) == NULL);
    Tests.run("werks_stringlist_take_last sl9 NO", werks_stringlist_take_last(sl9) == NULL);
    Tests.run("werks_stringlist_delete_last sl9 NO", !werks_stringlist_delete_last(sl9));
    Tests.run("werks_stringlist_drop_first sl9 3 NO", !werks_stringlist_drop_first(sl9, 3));
    Tests.run("werks_stringlist_drop_last sl9 3 NO", !werks_stringlist_drop_last(sl9, 3));
    Tests.run("werks_stringlist_get_size sl9 3", werks_stringlist_get_size(sl9) == 3);
    Tests.run("werks_stringlist_remove_empties sl9 NO", !werks_stringlist_remove_empties(sl9));
    Tests.run("werks_stringlist_count_empties sl9 1", werks_stringlist_count_empties(sl9) == 1);
    Tests.run("werks_stringlist_remove_duplicates sl9 NO", !werks_stringlist_remove_duplicates(sl9));
    Tests.run("werks_stringlist_count_duplicates sl9 1", werks_stringlist_count_duplicates(sl9) == 1);
    Tests.run("werks_stringlist_load_from_file sl9 NO", !werks_stringlist_read_from_file(sl9, "sltest.txt"));
    Tests.run("werks_stringlist_read_from_string sl9 NO", !werks_stringlist_read_from_string(sl9, "000,abd,def,ghi,ghi,123,456,789,000", ","));
    Tests.run("werks_stringlist_remove_once sl9 literal NO", !werks_stringlist_remove_once(sl9, "literal"));
    Tests.run("werks_stringlist_remove_all sl9 literal NO", !werks_stringlist_remove_all(sl9, "literal"));
    Tests.run("werks_stringlist_swap sl9 1 2 NO", !werks_stringlist_swap(sl9, 1, 2));
    Tests.run("werks_stringlist_move_first sl9 1 NO", !werks_stringlist_move_first(sl9, 1) && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_move_up sl9 2 NO", !werks_stringlist_move_up(sl9, 2) && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_move_down sl9 1 NO", !werks_stringlist_move_down(sl9, 1) && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_move_last sl9 1 NO", !werks_stringlist_move_last(sl9, 1) && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_format sl9 1 [] NO", !werks_stringlist_format(sl9, 1, "[%s]") && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_format_all sl9 <> NO", !werks_stringlist_format_all(sl9, "<%s>") && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_prefix_all sl9 ## NO", !werks_stringlist_prefix_all(sl9, "##") && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_suffix_all sl9 $$ NO", !werks_stringlist_suffix_all(sl9, "$$") && streq(werks_stringlist_get(sl9, 1), STRINGS_NOTHING));
    Tests.run("werks_stringlist_delete_from_to sl9 1 2 NO", !werks_stringlist_delete_from_to(sl9, 1, 2));
    Tests.run("werks_stringlist_extract_from_to sl9 1 2 NO", werks_stringlist_extract_from_to(sl9, 1, 2) == NULL);
    Tests.run("werks_stringlist_get_size sl9 3", werks_stringlist_get_size(sl9) == 3);
    Tests.run("werks_stringlist_reverse sl9 NO", !werks_stringlist_reverse(sl9));
    Tests.run("werks_stringlist_set sl9 0 NO", !werks_stringlist_set(sl9, 0, "TEST"));
    Tests.run("werks_stringlist_include sl9 literal2 NO", !werks_stringlist_include(sl9, "literal2"));
    werks_stringlist_dt* slZ = werks_stringlist_concatenate(sl9, sl9);
    Tests.run("werks_stringlist_concatenate slZ", assigned(slZ));
    Tests.run("werks_stringlist_get_size slZ 6", werks_stringlist_get_size(slZ) == 6);
    werks_stringlist_destroy(slZ);
    werks_stringlist_clear(sl9);
    Tests.run("werks_stringlist_clear sl9 NO", werks_stringlist_get_size(sl9) == 3);
    werks_stringlist_destroy(sl9);
    werks_stringlist_dt* sl0 = werks_stringlist_make();
    werks_stringlist_read_from_string(sl0, "--abd##,--def--,--ghi$$,zzz,000,--123$$,--456##,--789--", ",");
    Tests.run("werks_stringlist_get_size sl0 8", werks_stringlist_get_size(sl0) == 8);
    werks_stringlist_dt* sle0 = werks_stringlist_extract_prefixed(sl0, "--");
    Tests.run("werks_stringlist_get_size sl0 2", werks_stringlist_get_size(sl0) == 2);
    Tests.run("werks_stringlist_get_size sle0 6", werks_stringlist_get_size(sle0) == 6);
    werks_stringlist_dt* sle1 = werks_stringlist_extract_suffixed(sle0, "--");
    Tests.run("werks_stringlist_get_size sle0 4", werks_stringlist_get_size(sle0) == 4);
    Tests.run("werks_stringlist_get_size sle1 2", werks_stringlist_get_size(sle1) == 2);
    werks_stringlist_destroy(sle0);
    werks_stringlist_destroy(sle1);
    werks_stringlist_read_from_string(sl0, "--abd##,--def--,--ghi$$,zzz,000,--123$$,--456##,--789--", ",");
    Tests.run("werks_stringlist_get_size sl0 10", werks_stringlist_get_size(sl0) == 10);
    sle0 = werks_stringlist_extract_not_prefixed(sl0, "--");
    Tests.run("werks_stringlist_get_size sl0 6", werks_stringlist_get_size(sl0) == 6);
    Tests.run("werks_stringlist_get_size sle0 4", werks_stringlist_get_size(sle0) == 4);
    werks_stringlist_destroy(sle0);
    sle1 = werks_stringlist_extract_not_suffixed(sl0, "##");
    Tests.run("werks_stringlist_get_size sl0 2", werks_stringlist_get_size(sl0) == 2);
    Tests.run("werks_stringlist_get_size sle1 4", werks_stringlist_get_size(sle1) == 4);
    werks_stringlist_destroy(sle1);
    werks_stringlist_destroy(sl0);
    werks_stringlist_dt* slz = werks_stringlist_make();
    werks_stringlist_read_from_string(slz, "000,xxx,xxx,xxx,xxx,111", ",");
    werks_stringlist_dt* skz = werks_stringlist_clone(slz);
    Tests.run("werks_stringlist_replace_first_occurrence slz xxx yyy", werks_stringlist_replace_first_occurrence(slz, "xxx", "yyy"));
    AUTO_STRING(csv4, werks_stringlist_write_to_string(slz, ';'));
    Tests.run("werks_stringlist_write_to_string slz", streq(csv4, "000;yyy;xxx;xxx;xxx;111"));
    Tests.run("werks_stringlist_replace_last_occurrence slz xxx yyy", werks_stringlist_replace_last_occurrence(slz, "xxx", "yyy"));
    AUTO_STRING(csv5, werks_stringlist_write_to_string(slz, ';'));
    Tests.run("werks_stringlist_write_to_string slz", streq(csv5, "000;yyy;xxx;xxx;yyy;111"));
    Tests.run("werks_stringlist_replace_occurrences slz xxx yyy", werks_stringlist_replace_occurrences(slz, "xxx", "yyy"));
    AUTO_STRING(csv6, werks_stringlist_write_to_string(slz, ';'));
    Tests.run("werks_stringlist_write_to_string slz", streq(csv6, "000;yyy;yyy;yyy;yyy;111"));
    werks_stringlist_dt* sly = werks_stringlist_make();
    werks_stringlist_read_from_string(sly, "222,333,444", ",");
    Tests.run("werks_stringlist_replace_occurrences_with slz yyy sly", werks_stringlist_replace_occurrences_with(slz, "yyy", sly));
    AUTO_STRING(csv7, werks_stringlist_write_to_string(slz, ';'));
    Tests.run("werks_stringlist_write_to_string slz", streq(csv7, "000;222;333;444;222;333;444;222;333;444;222;333;444;111"));
    werks_stringlist_clear(sly);
    werks_stringlist_read_from_string(sly, "aa,bb", ",");
    Tests.run("werks_stringlist_replace_first_occurrence_with slz 222 sly", werks_stringlist_replace_first_occurrence_with(slz, "222", sly));
    AUTO_STRING(csv8, werks_stringlist_write_to_string(slz, ';'));
    Tests.run("werks_stringlist_write_to_string slz", streq(csv8, "000;aa;bb;333;444;222;333;444;222;333;444;222;333;444;111"));
    Tests.run("werks_stringlist_replace_last_occurrence_with slz 444 sly", werks_stringlist_replace_last_occurrence_with(slz, "444", sly));
    AUTO_STRING(csv9, werks_stringlist_write_to_string(slz, ';'));
    Tests.run("werks_stringlist_write_to_string slz", streq(csv9, "000;aa;bb;333;444;222;333;444;222;333;444;222;333;aa;bb;111"));
    werks_stringlist_destroy(sly);
    werks_stringlist_destroy(slz);
    werks_stringlist_dt* sky = werks_stringlist_make();
    werks_stringlist_read_from_string(sky, "aa||bb||cc", "||");
    Tests.run("werks_stringlist_replace_from_to_with", werks_stringlist_replace_from_to_with(skz, 1, 4, sky));
    AUTO_STRING(csvz, werks_stringlist_write_to_string(skz, ';'));
    Tests.run("werks_stringlist_write_to_string skz", streq(csvz, "000;aa;bb;cc;111"));
    werks_stringlist_destroy(sky);
    Tests.run("werks_stringlist_read_from_json_array_string NO null", !werks_stringlist_read_from_json_array_string(NULL, NULL));
    Tests.run("werks_stringlist_read_from_json_array_string skz NO null", !werks_stringlist_read_from_json_array_string(skz, NULL));
    Tests.run("werks_stringlist_read_from_json_array_string skz NO empty", !werks_stringlist_read_from_json_array_string(skz, ""));
    Tests.run("werks_stringlist_read_from_json_array_string skz YES array", werks_stringlist_read_from_json_array_string(skz, "[]"));
    Tests.run("werks_stringlist_read_from_json_array_string skz YES spaced array", werks_stringlist_read_from_json_array_string(skz, " [ ] "));
    Tests.run("werks_stringlist_read_from_json_array_string skz YES full", werks_stringlist_read_from_json_array_string(skz, "[\"xx\",\"yy\"]"));
    Tests.run("werks_stringlist_read_from_json_array_string skz YES spaces", werks_stringlist_read_from_json_array_string(skz, " [ \"zz\" ] "));
    Tests.run("werks_stringlist_write_to_json_array_string null", !werks_stringlist_write_to_json_array_string(NULL));
    AUTO_STRING(jasz, werks_stringlist_write_to_json_array_string(skz));
    Tests.run("werks_stringlist_write_to_json_array_string skz", streq(jasz, "[\"000\",\"aa\",\"bb\",\"cc\",\"111\",\"xx\",\"yy\",\"zz\"]"));
    werks_stringlist_clear(skz);
    AUTO_STRING(jesz, werks_stringlist_write_to_json_array_string(skz));
    Tests.run("werks_stringlist_write_to_json_array_string skz empty", streq(jesz, "[]"));
    Tests.run("werks_stringlist_formatted_append NO 1", !werks_stringlist_formatted_append(NULL, "[%s]", "world"));
    Tests.run("werks_stringlist_formatted_append NO 2", !werks_stringlist_formatted_append(skz, NULL, "world"));
    Tests.run("werks_stringlist_formatted_append YES", werks_stringlist_formatted_append(skz, "[%s]", "world"));
    Tests.run("werks_stringlist_formatted_prepend NO 1", !werks_stringlist_formatted_prepend(NULL, "<<%s>>", "hello"));
    Tests.run("werks_stringlist_formatted_prepend NO 2", !werks_stringlist_formatted_prepend(skz, NULL, "hello"));
    Tests.run("werks_stringlist_formatted_prepend YES", werks_stringlist_formatted_prepend(skz, "<<%s>>", "hello"));
    Tests.run("werks_stringlist_get 0", streq(werks_stringlist_get(skz, 0), "<<hello>>"));
    Tests.run("werks_stringlist_get 1", streq(werks_stringlist_get(skz, 1), "[world]"));
    Tests.run("werks_stringlist_formatted_set skz 0 NO 1", !werks_stringlist_formatted_set(NULL, 0, "<[%s]>", "TEST"));
    Tests.run("werks_stringlist_formatted_set skz 0 NO 2", !werks_stringlist_formatted_set(skz, 100, "<[%s]>", "TEST"));
    Tests.run("werks_stringlist_formatted_set skz 0 NO 3", !werks_stringlist_formatted_set(skz, 0, NULL, "TEST"));
    Tests.run("werks_stringlist_formatted_set skz 0 YES", werks_stringlist_formatted_set(skz, 0, "<[%s]>", "TEST"));
    Tests.run("werks_stringlist_get 0", streq(werks_stringlist_get(skz, 0), "<[TEST]>"));
    werks_stringlist_destroy(skz);
    werks_stringlist_dt* scr = werks_stringlist_make();
    werks_stringlist_read_from_string(scr, "Hello World,Test,Hello Mundo,Hola,Testing,Hey", ",");
    Tests.run("werks_stringlist_get_size scr 6", werks_stringlist_get_size(scr) == 6);
    Tests.run("werks_stringlist_remove_containing scr Test", werks_stringlist_remove_containing(scr, "Test"));
    Tests.run("werks_stringlist_get_size scr 4", werks_stringlist_get_size(scr) == 4);
    Tests.run("werks_stringlist_remove_not_containing scr He", werks_stringlist_remove_not_containing(scr, "He"));
    Tests.run("werks_stringlist_get_size scr 3", werks_stringlist_get_size(scr) == 3);
    werks_stringlist_destroy(scr);
    werks_stringlist_dt* sdr = werks_stringlist_make();
    werks_stringlist_read_from_string(sdr, "Hello World,Test,Hello Mundo,Hola,Testing,Hey", ",");
    Tests.run("werks_stringlist_get_size sdr 6", werks_stringlist_get_size(sdr) == 6);
    werks_stringlist_dt* srr = werks_stringlist_make();
    werks_stringlist_read_from_string(srr, "He,Test", ",");
    Tests.run("werks_stringlist_get_size srr 2", werks_stringlist_get_size(srr) == 2);
    Tests.run("werks_stringlist_remove_all_containing_any sdr srr", werks_stringlist_remove_all_containing_any(sdr, srr));
    Tests.run("werks_stringlist_get_size sdr 1", werks_stringlist_get_size(sdr) == 1);
    werks_stringlist_read_from_string(sdr, "Hello World,Test,Hello Mundo,Hola,Testing,Hey", ",");
    Tests.run("werks_stringlist_get_size sdr 7", werks_stringlist_get_size(sdr) == 7);
    Tests.run("werks_stringlist_remove_all_not_containing_any sdr srr", werks_stringlist_remove_all_not_containing_any(sdr, srr));
    Tests.run("werks_stringlist_get_size sdr 5", werks_stringlist_get_size(sdr) == 5);
    werks_stringlist_destroy(sdr);
    werks_stringlist_destroy(srr);
    return Tests.end();
}

