/**
 * C eXTRA LiBRARiES & TOOLS
 * Library: MeH
 * File: meh_literals-inc.h
 * Brief: part of MeH
 * Copyright (c) 2025 Javier Santo Domingo (j-a-s-d@coderesearchlabs.com)
 */

#pragma once

#ifndef MEH
#warning This is intended to be part of the MeH C Library.
#endif

static const char HEX_DIGITS[] = "0123456789abcdef";

/* MeH.LITERALS -- Bytes */

#define BYTES_00 ((uint8_t)0x00)
#define BYTES_01 ((uint8_t)0x01)
#define BYTES_02 ((uint8_t)0x02)
#define BYTES_03 ((uint8_t)0x03)
#define BYTES_04 ((uint8_t)0x04)
#define BYTES_05 ((uint8_t)0x05)
#define BYTES_06 ((uint8_t)0x06)
#define BYTES_07 ((uint8_t)0x07)
#define BYTES_08 ((uint8_t)0x08)
#define BYTES_09 ((uint8_t)0x09)
#define BYTES_0A ((uint8_t)0x0A)
#define BYTES_0B ((uint8_t)0x0B)
#define BYTES_0C ((uint8_t)0x0C)
#define BYTES_0D ((uint8_t)0x0D)
#define BYTES_0E ((uint8_t)0x0E)
#define BYTES_0F ((uint8_t)0x0F)
#define BYTES_10 ((uint8_t)0x10)
#define BYTES_11 ((uint8_t)0x11)
#define BYTES_12 ((uint8_t)0x12)
#define BYTES_13 ((uint8_t)0x13)
#define BYTES_14 ((uint8_t)0x14)
#define BYTES_15 ((uint8_t)0x15)
#define BYTES_16 ((uint8_t)0x16)
#define BYTES_17 ((uint8_t)0x17)
#define BYTES_18 ((uint8_t)0x18)
#define BYTES_19 ((uint8_t)0x19)
#define BYTES_1A ((uint8_t)0x1A)
#define BYTES_1B ((uint8_t)0x1B)
#define BYTES_1C ((uint8_t)0x1C)
#define BYTES_1D ((uint8_t)0x1D)
#define BYTES_1E ((uint8_t)0x1E)
#define BYTES_1F ((uint8_t)0x1F)
#define BYTES_20 ((uint8_t)0x20)
#define BYTES_21 ((uint8_t)0x21)
#define BYTES_22 ((uint8_t)0x22)
#define BYTES_23 ((uint8_t)0x23)
#define BYTES_24 ((uint8_t)0x24)
#define BYTES_25 ((uint8_t)0x25)
#define BYTES_26 ((uint8_t)0x26)
#define BYTES_27 ((uint8_t)0x27)
#define BYTES_28 ((uint8_t)0x28)
#define BYTES_29 ((uint8_t)0x29)
#define BYTES_2A ((uint8_t)0x2A)
#define BYTES_2B ((uint8_t)0x2B)
#define BYTES_2C ((uint8_t)0x2C)
#define BYTES_2D ((uint8_t)0x2D)
#define BYTES_2E ((uint8_t)0x2E)
#define BYTES_2F ((uint8_t)0x2F)
#define BYTES_30 ((uint8_t)0x30)
#define BYTES_31 ((uint8_t)0x31)
#define BYTES_32 ((uint8_t)0x32)
#define BYTES_33 ((uint8_t)0x33)
#define BYTES_34 ((uint8_t)0x34)
#define BYTES_35 ((uint8_t)0x35)
#define BYTES_36 ((uint8_t)0x36)
#define BYTES_37 ((uint8_t)0x37)
#define BYTES_38 ((uint8_t)0x38)
#define BYTES_39 ((uint8_t)0x39)
#define BYTES_3A ((uint8_t)0x3A)
#define BYTES_3B ((uint8_t)0x3B)
#define BYTES_3C ((uint8_t)0x3C)
#define BYTES_3D ((uint8_t)0x3D)
#define BYTES_3E ((uint8_t)0x3E)
#define BYTES_3F ((uint8_t)0x3F)
#define BYTES_40 ((uint8_t)0x40)
#define BYTES_41 ((uint8_t)0x41)
#define BYTES_42 ((uint8_t)0x42)
#define BYTES_43 ((uint8_t)0x43)
#define BYTES_44 ((uint8_t)0x44)
#define BYTES_45 ((uint8_t)0x45)
#define BYTES_46 ((uint8_t)0x46)
#define BYTES_47 ((uint8_t)0x47)
#define BYTES_48 ((uint8_t)0x48)
#define BYTES_49 ((uint8_t)0x49)
#define BYTES_4A ((uint8_t)0x4A)
#define BYTES_4B ((uint8_t)0x4B)
#define BYTES_4C ((uint8_t)0x4C)
#define BYTES_4D ((uint8_t)0x4D)
#define BYTES_4E ((uint8_t)0x4E)
#define BYTES_4F ((uint8_t)0x4F)
#define BYTES_50 ((uint8_t)0x50)
#define BYTES_51 ((uint8_t)0x51)
#define BYTES_52 ((uint8_t)0x52)
#define BYTES_53 ((uint8_t)0x53)
#define BYTES_54 ((uint8_t)0x54)
#define BYTES_55 ((uint8_t)0x55)
#define BYTES_56 ((uint8_t)0x56)
#define BYTES_57 ((uint8_t)0x57)
#define BYTES_58 ((uint8_t)0x58)
#define BYTES_59 ((uint8_t)0x59)
#define BYTES_5A ((uint8_t)0x5A)
#define BYTES_5B ((uint8_t)0x5B)
#define BYTES_5C ((uint8_t)0x5C)
#define BYTES_5D ((uint8_t)0x5D)
#define BYTES_5E ((uint8_t)0x5E)
#define BYTES_5F ((uint8_t)0x5F)
#define BYTES_60 ((uint8_t)0x60)
#define BYTES_61 ((uint8_t)0x61)
#define BYTES_62 ((uint8_t)0x62)
#define BYTES_63 ((uint8_t)0x63)
#define BYTES_64 ((uint8_t)0x64)
#define BYTES_65 ((uint8_t)0x65)
#define BYTES_66 ((uint8_t)0x66)
#define BYTES_67 ((uint8_t)0x67)
#define BYTES_68 ((uint8_t)0x68)
#define BYTES_69 ((uint8_t)0x69)
#define BYTES_6A ((uint8_t)0x6A)
#define BYTES_6B ((uint8_t)0x6B)
#define BYTES_6C ((uint8_t)0x6C)
#define BYTES_6D ((uint8_t)0x6D)
#define BYTES_6E ((uint8_t)0x6E)
#define BYTES_6F ((uint8_t)0x6F)
#define BYTES_70 ((uint8_t)0x70)
#define BYTES_71 ((uint8_t)0x71)
#define BYTES_72 ((uint8_t)0x72)
#define BYTES_73 ((uint8_t)0x73)
#define BYTES_74 ((uint8_t)0x74)
#define BYTES_75 ((uint8_t)0x75)
#define BYTES_76 ((uint8_t)0x76)
#define BYTES_77 ((uint8_t)0x77)
#define BYTES_78 ((uint8_t)0x78)
#define BYTES_79 ((uint8_t)0x79)
#define BYTES_7A ((uint8_t)0x7A)
#define BYTES_7B ((uint8_t)0x7B)
#define BYTES_7C ((uint8_t)0x7C)
#define BYTES_7D ((uint8_t)0x7D)
#define BYTES_7E ((uint8_t)0x7E)
#define BYTES_7F ((uint8_t)0x7F)
#define BYTES_80 ((uint8_t)0x80)
#define BYTES_81 ((uint8_t)0x81)
#define BYTES_82 ((uint8_t)0x82)
#define BYTES_83 ((uint8_t)0x83)
#define BYTES_84 ((uint8_t)0x84)
#define BYTES_85 ((uint8_t)0x85)
#define BYTES_86 ((uint8_t)0x86)
#define BYTES_87 ((uint8_t)0x87)
#define BYTES_88 ((uint8_t)0x88)
#define BYTES_89 ((uint8_t)0x89)
#define BYTES_8A ((uint8_t)0x8A)
#define BYTES_8B ((uint8_t)0x8B)
#define BYTES_8C ((uint8_t)0x8C)
#define BYTES_8D ((uint8_t)0x8D)
#define BYTES_8E ((uint8_t)0x8E)
#define BYTES_8F ((uint8_t)0x8F)
#define BYTES_90 ((uint8_t)0x90)
#define BYTES_91 ((uint8_t)0x91)
#define BYTES_92 ((uint8_t)0x92)
#define BYTES_93 ((uint8_t)0x93)
#define BYTES_94 ((uint8_t)0x94)
#define BYTES_95 ((uint8_t)0x95)
#define BYTES_96 ((uint8_t)0x96)
#define BYTES_97 ((uint8_t)0x97)
#define BYTES_98 ((uint8_t)0x98)
#define BYTES_99 ((uint8_t)0x99)
#define BYTES_9A ((uint8_t)0x9A)
#define BYTES_9B ((uint8_t)0x9B)
#define BYTES_9C ((uint8_t)0x9C)
#define BYTES_9D ((uint8_t)0x9D)
#define BYTES_9E ((uint8_t)0x9E)
#define BYTES_9F ((uint8_t)0x9F)
#define BYTES_A0 ((uint8_t)0xA0)
#define BYTES_A1 ((uint8_t)0xA1)
#define BYTES_A2 ((uint8_t)0xA2)
#define BYTES_A3 ((uint8_t)0xA3)
#define BYTES_A4 ((uint8_t)0xA4)
#define BYTES_A5 ((uint8_t)0xA5)
#define BYTES_A6 ((uint8_t)0xA6)
#define BYTES_A7 ((uint8_t)0xA7)
#define BYTES_A8 ((uint8_t)0xA8)
#define BYTES_A9 ((uint8_t)0xA9)
#define BYTES_AA ((uint8_t)0xAA)
#define BYTES_AB ((uint8_t)0xAB)
#define BYTES_AC ((uint8_t)0xAC)
#define BYTES_AD ((uint8_t)0xAD)
#define BYTES_AE ((uint8_t)0xAE)
#define BYTES_AF ((uint8_t)0xAF)
#define BYTES_B0 ((uint8_t)0xB0)
#define BYTES_B1 ((uint8_t)0xB1)
#define BYTES_B2 ((uint8_t)0xB2)
#define BYTES_B3 ((uint8_t)0xB3)
#define BYTES_B4 ((uint8_t)0xB4)
#define BYTES_B5 ((uint8_t)0xB5)
#define BYTES_B6 ((uint8_t)0xB6)
#define BYTES_B7 ((uint8_t)0xB7)
#define BYTES_B8 ((uint8_t)0xB8)
#define BYTES_B9 ((uint8_t)0xB9)
#define BYTES_BA ((uint8_t)0xBA)
#define BYTES_BB ((uint8_t)0xBB)
#define BYTES_BC ((uint8_t)0xBC)
#define BYTES_BD ((uint8_t)0xBD)
#define BYTES_BE ((uint8_t)0xBE)
#define BYTES_BF ((uint8_t)0xBF)
#define BYTES_C0 ((uint8_t)0xC0)
#define BYTES_C1 ((uint8_t)0xC1)
#define BYTES_C2 ((uint8_t)0xC2)
#define BYTES_C3 ((uint8_t)0xC3)
#define BYTES_C4 ((uint8_t)0xC4)
#define BYTES_C5 ((uint8_t)0xC5)
#define BYTES_C6 ((uint8_t)0xC6)
#define BYTES_C7 ((uint8_t)0xC7)
#define BYTES_C8 ((uint8_t)0xC8)
#define BYTES_C9 ((uint8_t)0xC9)
#define BYTES_CA ((uint8_t)0xCA)
#define BYTES_CB ((uint8_t)0xCB)
#define BYTES_CC ((uint8_t)0xCC)
#define BYTES_CD ((uint8_t)0xCD)
#define BYTES_CE ((uint8_t)0xCE)
#define BYTES_CF ((uint8_t)0xCF)
#define BYTES_D0 ((uint8_t)0xD0)
#define BYTES_D1 ((uint8_t)0xD1)
#define BYTES_D2 ((uint8_t)0xD2)
#define BYTES_D3 ((uint8_t)0xD3)
#define BYTES_D4 ((uint8_t)0xD4)
#define BYTES_D5 ((uint8_t)0xD5)
#define BYTES_D6 ((uint8_t)0xD6)
#define BYTES_D7 ((uint8_t)0xD7)
#define BYTES_D8 ((uint8_t)0xD8)
#define BYTES_D9 ((uint8_t)0xD9)
#define BYTES_DA ((uint8_t)0xDA)
#define BYTES_DB ((uint8_t)0xDB)
#define BYTES_DC ((uint8_t)0xDC)
#define BYTES_DD ((uint8_t)0xDD)
#define BYTES_DE ((uint8_t)0xDE)
#define BYTES_DF ((uint8_t)0xDF)
#define BYTES_E0 ((uint8_t)0xE0)
#define BYTES_E1 ((uint8_t)0xE1)
#define BYTES_E2 ((uint8_t)0xE2)
#define BYTES_E3 ((uint8_t)0xE3)
#define BYTES_E4 ((uint8_t)0xE4)
#define BYTES_E5 ((uint8_t)0xE5)
#define BYTES_E6 ((uint8_t)0xE6)
#define BYTES_E7 ((uint8_t)0xE7)
#define BYTES_E8 ((uint8_t)0xE8)
#define BYTES_E9 ((uint8_t)0xE9)
#define BYTES_EA ((uint8_t)0xEA)
#define BYTES_EB ((uint8_t)0xEB)
#define BYTES_EC ((uint8_t)0xEC)
#define BYTES_ED ((uint8_t)0xED)
#define BYTES_EE ((uint8_t)0xEE)
#define BYTES_EF ((uint8_t)0xEF)
#define BYTES_F0 ((uint8_t)0xF0)
#define BYTES_F1 ((uint8_t)0xF1)
#define BYTES_F2 ((uint8_t)0xF2)
#define BYTES_F3 ((uint8_t)0xF3)
#define BYTES_F4 ((uint8_t)0xF4)
#define BYTES_F5 ((uint8_t)0xF5)
#define BYTES_F6 ((uint8_t)0xF6)
#define BYTES_F7 ((uint8_t)0xF7)
#define BYTES_F8 ((uint8_t)0xF8)
#define BYTES_F9 ((uint8_t)0xF9)
#define BYTES_FA ((uint8_t)0xFA)
#define BYTES_FB ((uint8_t)0xFB)
#define BYTES_FC ((uint8_t)0xFC)
#define BYTES_FD ((uint8_t)0xFD)
#define BYTES_FE ((uint8_t)0xFE)
#define BYTES_FF ((uint8_t)0xFF)

/* MeH.LITERALS -- Characters */

// symbols
#define CHARS_NULL '\0'
#define CHARS_TAB '\t'
#define CHARS_LF '\n'
#define CHARS_CR '\r'
#define CHARS_SPACE ' '
#define CHARS_EQUAL '='
#define CHARS_NUMERAL '#'
#define CHARS_PIPE '|'
#define CHARS_MINUS '-'
#define CHARS_PLUS '+'
#define CHARS_PERCENT '%'
#define CHARS_DOLLAR '$'
#define CHARS_SLASH '/'
#define CHARS_BACKSLASH '\\'
#define CHARS_AMPERSAND '&'
#define CHARS_ASTERISK '*'
#define CHARS_UNDERSCORE '_'
#define CHARS_COLON ':'
#define CHARS_SEMICOLON ';'
#define CHARS_COMMA ','
#define CHARS_PERIOD '.'
#define CHARS_APOSTROPHE '\''
#define CHARS_QUOTE '\"'
#define CHARS_CARET '^'
#define CHARS_TILDE '~'
#define CHARS_AT '@'
#define CHARS_EXCLAMATION '!'
#define CHARS_QUESTION '?'
#define CHARS_MINOR '<'
#define CHARS_MAJOR '>'
#define CHARS_BRACES_OPEN '{'
#define CHARS_BRACES_CLOSE '}'
#define CHARS_BRACKETS_OPEN '['
#define CHARS_BRACKETS_CLOSE ']'
#define CHARS_PARENTHESES_OPEN '('
#define CHARS_PARENTHESES_CLOSE ')'
// numbers
#define CHARS_NUMBER_ZERO '0'
#define CHARS_NUMBER_ONE '1'
#define CHARS_NUMBER_TWO '2'
#define CHARS_NUMBER_THREE '3'
#define CHARS_NUMBER_FOUR '4'
#define CHARS_NUMBER_FIVE '5'
#define CHARS_NUMBER_SIX '6'
#define CHARS_NUMBER_SEVEN '7'
#define CHARS_NUMBER_EIGHT '8'
#define CHARS_NUMBER_NINE '9'
// uppercase letters
#define CHARS_UPPERCASE_A 'A'
#define CHARS_UPPERCASE_B 'B'
#define CHARS_UPPERCASE_C 'C'
#define CHARS_UPPERCASE_D 'D'
#define CHARS_UPPERCASE_E 'E'
#define CHARS_UPPERCASE_F 'F'
#define CHARS_UPPERCASE_G 'G'
#define CHARS_UPPERCASE_H 'H'
#define CHARS_UPPERCASE_I 'I'
#define CHARS_UPPERCASE_J 'J'
#define CHARS_UPPERCASE_K 'K'
#define CHARS_UPPERCASE_L 'L'
#define CHARS_UPPERCASE_M 'M'
#define CHARS_UPPERCASE_N 'N'
#define CHARS_UPPERCASE_O 'O'
#define CHARS_UPPERCASE_P 'P'
#define CHARS_UPPERCASE_Q 'Q'
#define CHARS_UPPERCASE_R 'R'
#define CHARS_UPPERCASE_S 'S'
#define CHARS_UPPERCASE_T 'T'
#define CHARS_UPPERCASE_U 'U'
#define CHARS_UPPERCASE_V 'V'
#define CHARS_UPPERCASE_W 'W'
#define CHARS_UPPERCASE_X 'X'
#define CHARS_UPPERCASE_Y 'Y'
#define CHARS_UPPERCASE_Z 'Z'
// lowercase letters
#define CHARS_LOWERCASE_A 'a'
#define CHARS_LOWERCASE_B 'b'
#define CHARS_LOWERCASE_C 'c'
#define CHARS_LOWERCASE_D 'd'
#define CHARS_LOWERCASE_E 'e'
#define CHARS_LOWERCASE_F 'f'
#define CHARS_LOWERCASE_G 'g'
#define CHARS_LOWERCASE_H 'h'
#define CHARS_LOWERCASE_I 'i'
#define CHARS_LOWERCASE_J 'j'
#define CHARS_LOWERCASE_K 'k'
#define CHARS_LOWERCASE_L 'l'
#define CHARS_LOWERCASE_M 'm'
#define CHARS_LOWERCASE_N 'n'
#define CHARS_LOWERCASE_O 'o'
#define CHARS_LOWERCASE_P 'p'
#define CHARS_LOWERCASE_Q 'q'
#define CHARS_LOWERCASE_R 'r'
#define CHARS_LOWERCASE_S 's'
#define CHARS_LOWERCASE_T 't'
#define CHARS_LOWERCASE_U 'u'
#define CHARS_LOWERCASE_V 'v'
#define CHARS_LOWERCASE_W 'w'
#define CHARS_LOWERCASE_X 'x'
#define CHARS_LOWERCASE_Y 'y'
#define CHARS_LOWERCASE_Z 'z'

/* MeH.LITERALS -- Strings */

// special
#define STRINGS_NOTHING ""
#define STRINGS_NULL "\0"
#define STRINGS_TAB "\t"
#define STRINGS_LF "\n"
#define STRINGS_CR "\r"
#define STRINGS_SPACE " "
// symbols
#define STRINGS_BACKTICK "`"
#define STRINGS_DIAERESIS "¨"
#define STRINGS_EQUAL "="
#define STRINGS_NUMERAL "#"
#define STRINGS_PIPE "|"
#define STRINGS_MINUS "-"
#define STRINGS_PLUS "+"
#define STRINGS_PERCENT "%"
#define STRINGS_DOLLAR "$"
#define STRINGS_SLASH "/"
#define STRINGS_BACKSLASH "\\"
#define STRINGS_AMPERSAND "&"
#define STRINGS_ASTERISK "*"
#define STRINGS_UNDERSCORE "_"
#define STRINGS_COLON ":"
#define STRINGS_SEMICOLON ";"
#define STRINGS_COMMA ","
#define STRINGS_PERIOD "."
#define STRINGS_APOSTROPHE "'"
#define STRINGS_QUOTE "\""
#define STRINGS_CARET "^"
#define STRINGS_TILDE "~"
#define STRINGS_AT "@"
#define STRINGS_EXCLAMATION "!"
#define STRINGS_QUESTION "?"
#define STRINGS_MINOR "<"
#define STRINGS_MAJOR ">"
#define STRINGS_BRACES_OPEN "{"
#define STRINGS_BRACES_CLOSE "}"
#define STRINGS_BRACKETS_OPEN "["
#define STRINGS_BRACKETS_CLOSE "]"
#define STRINGS_PARENTHESES_OPEN "("
#define STRINGS_PARENTHESES_CLOSE ")"
// numbers
#define STRINGS_NUMBER_ZERO "0"
#define STRINGS_NUMBER_ONE "1"
#define STRINGS_NUMBER_TWO "2"
#define STRINGS_NUMBER_THREE "3"
#define STRINGS_NUMBER_FOUR "4"
#define STRINGS_NUMBER_FIVE "5"
#define STRINGS_NUMBER_SIX "6"
#define STRINGS_NUMBER_SEVEN "7"
#define STRINGS_NUMBER_EIGHT "8"
#define STRINGS_NUMBER_NINE "9"
// uppercase letters  
#define STRINGS_UPPERCASE_A "A"
#define STRINGS_UPPERCASE_B "B"
#define STRINGS_UPPERCASE_C "C"
#define STRINGS_UPPERCASE_D "D"
#define STRINGS_UPPERCASE_E "E"
#define STRINGS_UPPERCASE_F "F"
#define STRINGS_UPPERCASE_G "G"
#define STRINGS_UPPERCASE_H "H"
#define STRINGS_UPPERCASE_I "I"
#define STRINGS_UPPERCASE_J "J"
#define STRINGS_UPPERCASE_K "K"
#define STRINGS_UPPERCASE_L "L"
#define STRINGS_UPPERCASE_M "M"
#define STRINGS_UPPERCASE_N "N"
#define STRINGS_UPPERCASE_O "O"
#define STRINGS_UPPERCASE_P "P"
#define STRINGS_UPPERCASE_Q "Q"
#define STRINGS_UPPERCASE_R "R"
#define STRINGS_UPPERCASE_S "S"
#define STRINGS_UPPERCASE_T "T"
#define STRINGS_UPPERCASE_U "U"
#define STRINGS_UPPERCASE_V "V"
#define STRINGS_UPPERCASE_W "W"
#define STRINGS_UPPERCASE_X "X"
#define STRINGS_UPPERCASE_Y "Y"
#define STRINGS_UPPERCASE_Z "Z"
// lowercase letters
#define STRINGS_LOWERCASE_A "a"
#define STRINGS_LOWERCASE_B "b"
#define STRINGS_LOWERCASE_C "c"
#define STRINGS_LOWERCASE_D "d"
#define STRINGS_LOWERCASE_E "e"
#define STRINGS_LOWERCASE_F "f"
#define STRINGS_LOWERCASE_G "g"
#define STRINGS_LOWERCASE_H "h"
#define STRINGS_LOWERCASE_I "i"
#define STRINGS_LOWERCASE_J "j"
#define STRINGS_LOWERCASE_K "k"
#define STRINGS_LOWERCASE_L "l"
#define STRINGS_LOWERCASE_M "m"
#define STRINGS_LOWERCASE_N "n"
#define STRINGS_LOWERCASE_O "o"
#define STRINGS_LOWERCASE_P "p"
#define STRINGS_LOWERCASE_Q "q"
#define STRINGS_LOWERCASE_R "r"
#define STRINGS_LOWERCASE_S "s"
#define STRINGS_LOWERCASE_T "t"
#define STRINGS_LOWERCASE_U "u"
#define STRINGS_LOWERCASE_V "v"
#define STRINGS_LOWERCASE_W "w"
#define STRINGS_LOWERCASE_X "x"
#define STRINGS_LOWERCASE_Y "y"
#define STRINGS_LOWERCASE_Z "z"

