const char* math_h_name = "math.h";

const char* math_h_globals[] = {
    // <math.h> declares mathematical functions and macros,
    // but it does NOT define any global variables with external linkage.
    NULL
};

// Types declared in math.h
const char* math_h_types[] = {
    // math.h does not declare new types except possibly extern int signgam;
    NULL
};

// Macros declared in math.h
const char* math_h_macros[] = {
    "HUGE_VAL",
    "HUGE_VALF",
    "HUGE_VALL",
    "INFINITY",
    "NAN",
    "M_E",
    "M_LOG2E",
    "M_LOG10E",
    "M_LN2",
    "M_LN10",
    "M_PI",
    "M_PI_2",
    "M_PI_4",
    "M_1_PI",
    "M_2_PI",
    "M_2_SQRTPI",
    "M_SQRT2",
    "M_SQRT1_2",
    "MAXFLOAT",
    "FLT_EVAL_METHOD",
    "FP_FAST_FMA",
    "FP_FAST_FMAF",
    "FP_FAST_FMAL",
    "FP_ILOGB0",
    "FP_ILOGBNAN",
    "FP_INFINITE",
    "FP_NAN",
    "FP_NORMAL",
    "FP_SUBNORMAL",
    "FP_ZERO",
    "math_errhandling",
    "MATH_ERRNO",
    "MATH_ERREXCEPT",
    NULL
};

// Functions declared in math.h
const char* math_h_functions[] = {
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "cbrt",
    "ceil",
    "copysign",
    "cos",
    "cosh",
    "erf",
    "erfc",
    "exp",
    "expm1",
    "fabs",
    "fdim",
    "floor",
    "fma",
    "fmax",
    "fmin",
    "fmod",
    "frexp",
    "gamma",
    "hypot",
    "ilogb",
    "isfinite",
    "isgreater",
    "isgreaterequal",
    "isless",
    "islessequal",
    "islessgreater",
    "isnormal",
    "isnan",
    "j0",
    "j1",
    "jn",
    "ldexp",
    "lgamma",
    "llrint",
    "llround",
    "log",
    "log10",
    "log1p",
    "log2",
    "logb",
    "lrint",
    "lround",
    "modf",
    "nan",
    "nanf",
    "nanl",
    "nearbyint",
    "nextafter",
    "nexttoward",
    "pow",
    "remainder",
    "remquo",
    "rint",
    "round",
    "scalbln",
    "scalbn",
    "signbit",
    "sin",
    "sinh",
    "sqrt",
    "tan",
    "tanh",
    "tgamma",
    "trunc",
    "y0",
    "y1",
    "yn",
    // c23 floating-point math functions
    "acospi",
    "asinpi",
    "atanpi",
    "atan2pi",
    "cospi",
    "sinpi",
    "tanpi",
    "exp10",
    "exp10m1",
    "exp2m1",
    "log10p1",
    "logp1",
    "log2p1",
    "rsqrt",
    "pown",
    "powr",
    "rootn",
    "roundeven",
    "nextup",
    "nextdown",
    "totalorder",
    "totalordermag",
    "getpayload",
    "setpayload",
    "iscannonical",
    "issignaling",
    "issubnormal",
    "iszero",
    "llogb",
    "fsqrt",
    NULL
};

